// This file is auto-generated by @hey-api/openapi-ts

import {
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  authConfirmLoginEmail,
  authForgotPassword,
  authLogin,
  authLogout,
  authOauthGithubCallback,
  authOauthGithubStart,
  authOauthGoogleCallback,
  authOauthGoogleStart,
  authOauthLink,
  authRegister,
  authResendVerification,
  authResetPassword,
  authSession,
  authVerifyEmail,
  createCollection,
  createItem,
  cspReport,
  deleteAccount,
  deleteCollection,
  deleteItem,
  getActivity,
  getCollection,
  getHealth,
  getItem,
  getItemContent,
  getItemDetails,
  getPreferences,
  getReadiness,
  getStats,
  globalSearch,
  listCollections,
  listItems,
  type Options,
  setCollectionFavorite,
  setItemFavorite,
  setItemPinned,
  updateCollection,
  updateItem,
  updatePreferences,
  updateProfile,
} from "../sdk.gen";
import type {
  AuthConfirmLoginEmailData,
  AuthConfirmLoginEmailError,
  AuthConfirmLoginEmailResponse,
  AuthForgotPasswordData,
  AuthForgotPasswordError,
  AuthForgotPasswordResponse,
  AuthLoginData,
  AuthLoginError,
  AuthLoginResponse,
  AuthLogoutData,
  AuthLogoutError,
  AuthLogoutResponse,
  AuthOauthGithubCallbackData,
  AuthOauthGithubCallbackError,
  AuthOauthGithubCallbackResponse,
  AuthOauthGithubStartData,
  AuthOauthGithubStartError,
  AuthOauthGithubStartResponse,
  AuthOauthGoogleCallbackData,
  AuthOauthGoogleCallbackError,
  AuthOauthGoogleCallbackResponse,
  AuthOauthGoogleStartData,
  AuthOauthGoogleStartError,
  AuthOauthGoogleStartResponse,
  AuthOauthLinkData,
  AuthOauthLinkError,
  AuthOauthLinkResponse,
  AuthRegisterData,
  AuthRegisterError,
  AuthRegisterResponse,
  AuthResendVerificationData,
  AuthResendVerificationError,
  AuthResendVerificationResponse,
  AuthResetPasswordData,
  AuthResetPasswordError,
  AuthResetPasswordResponse,
  AuthSessionData,
  AuthSessionError,
  AuthSessionResponse,
  AuthVerifyEmailData,
  AuthVerifyEmailError,
  AuthVerifyEmailResponse,
  CreateCollectionData,
  CreateCollectionError,
  CreateCollectionResponse,
  CreateItemData,
  CreateItemError,
  CreateItemResponse,
  CspReportData,
  CspReportError,
  CspReportResponse,
  DeleteAccountData,
  DeleteAccountError,
  DeleteAccountResponse,
  DeleteCollectionData,
  DeleteCollectionError,
  DeleteCollectionResponse,
  DeleteItemData,
  DeleteItemError,
  DeleteItemResponse,
  GetActivityData,
  GetActivityError,
  GetActivityResponse,
  GetCollectionData,
  GetCollectionError,
  GetCollectionResponse,
  GetHealthData,
  GetHealthError,
  GetHealthResponse,
  GetItemContentData,
  GetItemContentError,
  GetItemContentResponse,
  GetItemData,
  GetItemDetailsData,
  GetItemDetailsError,
  GetItemDetailsResponse,
  GetItemError,
  GetItemResponse,
  GetPreferencesData,
  GetPreferencesError,
  GetPreferencesResponse,
  GetReadinessData,
  GetReadinessError,
  GetReadinessResponse,
  GetStatsData,
  GetStatsError,
  GetStatsResponse,
  GlobalSearchData,
  GlobalSearchError,
  GlobalSearchResponse,
  ListCollectionsData,
  ListCollectionsError,
  ListCollectionsResponse,
  ListItemsData,
  ListItemsError,
  ListItemsResponse,
  SetCollectionFavoriteData,
  SetCollectionFavoriteError,
  SetCollectionFavoriteResponse,
  SetItemFavoriteData,
  SetItemFavoriteError,
  SetItemFavoriteResponse,
  SetItemPinnedData,
  SetItemPinnedError,
  SetItemPinnedResponse,
  UpdateCollectionData,
  UpdateCollectionError,
  UpdateCollectionResponse,
  UpdateItemData,
  UpdateItemError,
  UpdateItemResponse,
  UpdatePreferencesData,
  UpdatePreferencesError,
  UpdatePreferencesResponse,
  UpdateProfileData,
  UpdateProfileError,
  UpdateProfileResponse,
} from "../types.gen";

/**
 * Confirm a credential sign-in email
 */
export const authConfirmLoginEmailMutation = (
  options?: Partial<Options<AuthConfirmLoginEmailData>>,
): UseMutationOptions<
  AuthConfirmLoginEmailResponse,
  AuthConfirmLoginEmailError,
  Options<AuthConfirmLoginEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthConfirmLoginEmailResponse,
    AuthConfirmLoginEmailError,
    Options<AuthConfirmLoginEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authConfirmLoginEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Request a password reset link
 */
export const authForgotPasswordMutation = (
  options?: Partial<Options<AuthForgotPasswordData>>,
): UseMutationOptions<
  AuthForgotPasswordResponse,
  AuthForgotPasswordError,
  Options<AuthForgotPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthForgotPasswordResponse,
    AuthForgotPasswordError,
    Options<AuthForgotPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authForgotPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Confirm and link a pending OAuth account with a password
 */
export const authOauthLinkMutation = (
  options?: Partial<Options<AuthOauthLinkData>>,
): UseMutationOptions<
  AuthOauthLinkResponse,
  AuthOauthLinkError,
  Options<AuthOauthLinkData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthOauthLinkResponse,
    AuthOauthLinkError,
    Options<AuthOauthLinkData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authOauthLink({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Log in with email and password
 */
export const authLoginMutation = (
  options?: Partial<Options<AuthLoginData>>,
): UseMutationOptions<
  AuthLoginResponse,
  AuthLoginError,
  Options<AuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthLoginResponse,
    AuthLoginError,
    Options<AuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Log out of the current session
 */
export const authLogoutMutation = (
  options?: Partial<Options<AuthLogoutData>>,
): UseMutationOptions<
  AuthLogoutResponse,
  AuthLogoutError,
  Options<AuthLogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthLogoutResponse,
    AuthLogoutError,
    Options<AuthLogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authLogout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const authOauthGithubCallbackQueryKey = (
  options?: Options<AuthOauthGithubCallbackData>,
) => createQueryKey("authOauthGithubCallback", options);

/**
 * Complete github OAuth sign-in
 */
export const authOauthGithubCallbackOptions = (
  options?: Options<AuthOauthGithubCallbackData>,
) =>
  queryOptions<
    AuthOauthGithubCallbackResponse,
    AuthOauthGithubCallbackError,
    AuthOauthGithubCallbackResponse,
    ReturnType<typeof authOauthGithubCallbackQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authOauthGithubCallback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authOauthGithubCallbackQueryKey(options),
  });

export const authOauthGithubStartQueryKey = (
  options?: Options<AuthOauthGithubStartData>,
) => createQueryKey("authOauthGithubStart", options);

/**
 * Begin github OAuth sign-in
 */
export const authOauthGithubStartOptions = (
  options?: Options<AuthOauthGithubStartData>,
) =>
  queryOptions<
    AuthOauthGithubStartResponse,
    AuthOauthGithubStartError,
    AuthOauthGithubStartResponse,
    ReturnType<typeof authOauthGithubStartQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authOauthGithubStart({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authOauthGithubStartQueryKey(options),
  });

export const authOauthGoogleCallbackQueryKey = (
  options?: Options<AuthOauthGoogleCallbackData>,
) => createQueryKey("authOauthGoogleCallback", options);

/**
 * Complete google OAuth sign-in
 */
export const authOauthGoogleCallbackOptions = (
  options?: Options<AuthOauthGoogleCallbackData>,
) =>
  queryOptions<
    AuthOauthGoogleCallbackResponse,
    AuthOauthGoogleCallbackError,
    AuthOauthGoogleCallbackResponse,
    ReturnType<typeof authOauthGoogleCallbackQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authOauthGoogleCallback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authOauthGoogleCallbackQueryKey(options),
  });

export const authOauthGoogleStartQueryKey = (
  options?: Options<AuthOauthGoogleStartData>,
) => createQueryKey("authOauthGoogleStart", options);

/**
 * Begin google OAuth sign-in
 */
export const authOauthGoogleStartOptions = (
  options?: Options<AuthOauthGoogleStartData>,
) =>
  queryOptions<
    AuthOauthGoogleStartResponse,
    AuthOauthGoogleStartError,
    AuthOauthGoogleStartResponse,
    ReturnType<typeof authOauthGoogleStartQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authOauthGoogleStart({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authOauthGoogleStartQueryKey(options),
  });

/**
 * Register a new account
 */
export const authRegisterMutation = (
  options?: Partial<Options<AuthRegisterData>>,
): UseMutationOptions<
  AuthRegisterResponse,
  AuthRegisterError,
  Options<AuthRegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthRegisterResponse,
    AuthRegisterError,
    Options<AuthRegisterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authRegister({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Resend the email verification link
 */
export const authResendVerificationMutation = (
  options?: Partial<Options<AuthResendVerificationData>>,
): UseMutationOptions<
  AuthResendVerificationResponse,
  AuthResendVerificationError,
  Options<AuthResendVerificationData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthResendVerificationResponse,
    AuthResendVerificationError,
    Options<AuthResendVerificationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authResendVerification({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reset a password with a token
 */
export const authResetPasswordMutation = (
  options?: Partial<Options<AuthResetPasswordData>>,
): UseMutationOptions<
  AuthResetPasswordResponse,
  AuthResetPasswordError,
  Options<AuthResetPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthResetPasswordResponse,
    AuthResetPasswordError,
    Options<AuthResetPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authResetPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const authSessionQueryKey = (options?: Options<AuthSessionData>) =>
  createQueryKey("authSession", options);

/**
 * Get the current session user
 */
export const authSessionOptions = (options?: Options<AuthSessionData>) =>
  queryOptions<
    AuthSessionResponse,
    AuthSessionError,
    AuthSessionResponse,
    ReturnType<typeof authSessionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await authSession({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authSessionQueryKey(options),
  });

/**
 * Confirm an email verification token
 */
export const authVerifyEmailMutation = (
  options?: Partial<Options<AuthVerifyEmailData>>,
): UseMutationOptions<
  AuthVerifyEmailResponse,
  AuthVerifyEmailError,
  Options<AuthVerifyEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthVerifyEmailResponse,
    AuthVerifyEmailError,
    Options<AuthVerifyEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await authVerifyEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listCollectionsQueryKey = (
  options?: Options<ListCollectionsData>,
) => createQueryKey("listCollections", options);

/**
 * List all collections
 */
export const listCollectionsOptions = (
  options?: Options<ListCollectionsData>,
) =>
  queryOptions<
    ListCollectionsResponse,
    ListCollectionsError,
    ListCollectionsResponse,
    ReturnType<typeof listCollectionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listCollections({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listCollectionsQueryKey(options),
  });

/**
 * Create a collection
 */
export const createCollectionMutation = (
  options?: Partial<Options<CreateCollectionData>>,
): UseMutationOptions<
  CreateCollectionResponse,
  CreateCollectionError,
  Options<CreateCollectionData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateCollectionResponse,
    CreateCollectionError,
    Options<CreateCollectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createCollection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a collection
 */
export const deleteCollectionMutation = (
  options?: Partial<Options<DeleteCollectionData>>,
): UseMutationOptions<
  DeleteCollectionResponse,
  DeleteCollectionError,
  Options<DeleteCollectionData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteCollectionResponse,
    DeleteCollectionError,
    Options<DeleteCollectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteCollection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCollectionQueryKey = (options: Options<GetCollectionData>) =>
  createQueryKey("getCollection", options);

/**
 * Get a single collection
 */
export const getCollectionOptions = (options: Options<GetCollectionData>) =>
  queryOptions<
    GetCollectionResponse,
    GetCollectionError,
    GetCollectionResponse,
    ReturnType<typeof getCollectionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCollection({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCollectionQueryKey(options),
  });

/**
 * Update a collection
 */
export const updateCollectionMutation = (
  options?: Partial<Options<UpdateCollectionData>>,
): UseMutationOptions<
  UpdateCollectionResponse,
  UpdateCollectionError,
  Options<UpdateCollectionData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateCollectionResponse,
    UpdateCollectionError,
    Options<UpdateCollectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateCollection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Toggle a collection's favorite flag
 */
export const setCollectionFavoriteMutation = (
  options?: Partial<Options<SetCollectionFavoriteData>>,
): UseMutationOptions<
  SetCollectionFavoriteResponse,
  SetCollectionFavoriteError,
  Options<SetCollectionFavoriteData>
> => {
  const mutationOptions: UseMutationOptions<
    SetCollectionFavoriteResponse,
    SetCollectionFavoriteError,
    Options<SetCollectionFavoriteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setCollectionFavorite({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Ingest CSP violation reports
 *
 * Best-effort sink for browser Content-Security-Policy violation reports (Reporting API `report-to`). Rate-limited per IP; logs and discards; never reads a session or the database.
 */
export const cspReportMutation = (
  options?: Partial<Options<CspReportData>>,
): UseMutationOptions<
  CspReportResponse,
  CspReportError,
  Options<CspReportData>
> => {
  const mutationOptions: UseMutationOptions<
    CspReportResponse,
    CspReportError,
    Options<CspReportData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cspReport({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) =>
  createQueryKey("getHealth", options);

/**
 * Liveness check
 */
export const getHealthOptions = (options?: Options<GetHealthData>) =>
  queryOptions<
    GetHealthResponse,
    GetHealthError,
    GetHealthResponse,
    ReturnType<typeof getHealthQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHealthQueryKey(options),
  });

export const listItemsQueryKey = (options: Options<ListItemsData>) =>
  createQueryKey("listItems", options);

/**
 * List items (recent, by type, by collection, or favorites)
 */
export const listItemsOptions = (options: Options<ListItemsData>) =>
  queryOptions<
    ListItemsResponse,
    ListItemsError,
    ListItemsResponse,
    ReturnType<typeof listItemsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listItems({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listItemsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listItemsInfiniteQueryKey = (
  options: Options<ListItemsData>,
): QueryKey<Options<ListItemsData>> =>
  createQueryKey("listItems", options, true);

/**
 * List items (recent, by type, by collection, or favorites)
 */
export const listItemsInfiniteOptions = (options: Options<ListItemsData>) => {
  const opts = infiniteQueryOptions<
    ListItemsResponse,
    ListItemsError,
    InfiniteData<ListItemsResponse>,
    QueryKey<Options<ListItemsData>>,
    | string
    | Pick<
        QueryKey<Options<ListItemsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListItemsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listItems({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listItemsInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, "initialData">;
};

/**
 * Create an item
 */
export const createItemMutation = (
  options?: Partial<Options<CreateItemData>>,
): UseMutationOptions<
  CreateItemResponse,
  CreateItemError,
  Options<CreateItemData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateItemResponse,
    CreateItemError,
    Options<CreateItemData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createItem({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an item
 */
export const deleteItemMutation = (
  options?: Partial<Options<DeleteItemData>>,
): UseMutationOptions<
  DeleteItemResponse,
  DeleteItemError,
  Options<DeleteItemData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteItemResponse,
    DeleteItemError,
    Options<DeleteItemData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteItem({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getItemQueryKey = (options: Options<GetItemData>) =>
  createQueryKey("getItem", options);

/**
 * Get a single item
 */
export const getItemOptions = (options: Options<GetItemData>) =>
  queryOptions<
    GetItemResponse,
    GetItemError,
    GetItemResponse,
    ReturnType<typeof getItemQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getItem({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getItemQueryKey(options),
  });

/**
 * Update an item
 */
export const updateItemMutation = (
  options?: Partial<Options<UpdateItemData>>,
): UseMutationOptions<
  UpdateItemResponse,
  UpdateItemError,
  Options<UpdateItemData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateItemResponse,
    UpdateItemError,
    Options<UpdateItemData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateItem({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getItemContentQueryKey = (options: Options<GetItemContentData>) =>
  createQueryKey("getItemContent", options);

/**
 * Get an item's content
 */
export const getItemContentOptions = (options: Options<GetItemContentData>) =>
  queryOptions<
    GetItemContentResponse,
    GetItemContentError,
    GetItemContentResponse,
    ReturnType<typeof getItemContentQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getItemContent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getItemContentQueryKey(options),
  });

export const getItemDetailsQueryKey = (options: Options<GetItemDetailsData>) =>
  createQueryKey("getItemDetails", options);

/**
 * Get an item's details
 */
export const getItemDetailsOptions = (options: Options<GetItemDetailsData>) =>
  queryOptions<
    GetItemDetailsResponse,
    GetItemDetailsError,
    GetItemDetailsResponse,
    ReturnType<typeof getItemDetailsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getItemDetails({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getItemDetailsQueryKey(options),
  });

/**
 * Toggle an item's favorite flag
 */
export const setItemFavoriteMutation = (
  options?: Partial<Options<SetItemFavoriteData>>,
): UseMutationOptions<
  SetItemFavoriteResponse,
  SetItemFavoriteError,
  Options<SetItemFavoriteData>
> => {
  const mutationOptions: UseMutationOptions<
    SetItemFavoriteResponse,
    SetItemFavoriteError,
    Options<SetItemFavoriteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setItemFavorite({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Toggle an item's pinned flag
 */
export const setItemPinnedMutation = (
  options?: Partial<Options<SetItemPinnedData>>,
): UseMutationOptions<
  SetItemPinnedResponse,
  SetItemPinnedError,
  Options<SetItemPinnedData>
> => {
  const mutationOptions: UseMutationOptions<
    SetItemPinnedResponse,
    SetItemPinnedError,
    Options<SetItemPinnedData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setItemPinned({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete the current user's account
 */
export const deleteAccountMutation = (
  options?: Partial<Options<DeleteAccountData>>,
): UseMutationOptions<
  DeleteAccountResponse,
  DeleteAccountError,
  Options<DeleteAccountData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteAccountResponse,
    DeleteAccountError,
    Options<DeleteAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPreferencesQueryKey = (options?: Options<GetPreferencesData>) =>
  createQueryKey("getPreferences", options);

/**
 * Get the current user's editor preferences
 */
export const getPreferencesOptions = (options?: Options<GetPreferencesData>) =>
  queryOptions<
    GetPreferencesResponse,
    GetPreferencesError,
    GetPreferencesResponse,
    ReturnType<typeof getPreferencesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPreferences({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPreferencesQueryKey(options),
  });

/**
 * Update the current user's editor preferences
 */
export const updatePreferencesMutation = (
  options?: Partial<Options<UpdatePreferencesData>>,
): UseMutationOptions<
  UpdatePreferencesResponse,
  UpdatePreferencesError,
  Options<UpdatePreferencesData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdatePreferencesResponse,
    UpdatePreferencesError,
    Options<UpdatePreferencesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updatePreferences({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update the current user's profile
 */
export const updateProfileMutation = (
  options?: Partial<Options<UpdateProfileData>>,
): UseMutationOptions<
  UpdateProfileResponse,
  UpdateProfileError,
  Options<UpdateProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateProfileResponse,
    UpdateProfileError,
    Options<UpdateProfileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getReadinessQueryKey = (options?: Options<GetReadinessData>) =>
  createQueryKey("getReadiness", options);

/**
 * Readiness check
 */
export const getReadinessOptions = (options?: Options<GetReadinessData>) =>
  queryOptions<
    GetReadinessResponse,
    GetReadinessError,
    GetReadinessResponse,
    ReturnType<typeof getReadinessQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getReadiness({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getReadinessQueryKey(options),
  });

export const globalSearchQueryKey = (options: Options<GlobalSearchData>) =>
  createQueryKey("globalSearch", options);

/**
 * Search items and collections
 */
export const globalSearchOptions = (options: Options<GlobalSearchData>) =>
  queryOptions<
    GlobalSearchResponse,
    GlobalSearchError,
    GlobalSearchResponse,
    ReturnType<typeof globalSearchQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await globalSearch({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: globalSearchQueryKey(options),
  });

export const getStatsQueryKey = (options?: Options<GetStatsData>) =>
  createQueryKey("getStats", options);

/**
 * Get the current user's dashboard stats
 */
export const getStatsOptions = (options?: Options<GetStatsData>) =>
  queryOptions<
    GetStatsResponse,
    GetStatsError,
    GetStatsResponse,
    ReturnType<typeof getStatsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStats({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStatsQueryKey(options),
  });

export const getActivityQueryKey = (options?: Options<GetActivityData>) =>
  createQueryKey("getActivity", options);

/**
 * Get the current user's per-day item-creation activity
 */
export const getActivityOptions = (options?: Options<GetActivityData>) =>
  queryOptions<
    GetActivityResponse,
    GetActivityError,
    GetActivityResponse,
    ReturnType<typeof getActivityQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getActivity({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getActivityQueryKey(options),
  });
