import type { Item, Collection, ItemType, ItemCollection } from '@/types/item'

export const mockUser = {
    id: 'user_1',
    email: 'demo@devstash.io',
    name: 'John Doe',
    isPro: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
};

export const mockItemTypes: ItemType[] = [
    {
        id: 'type_1',
        name: 'snippet',
        icon: 'Code',
        color: '#3b82f6',
        isSystem: true,
        userId: null,
    },
    {
        id: 'type_2',
        name: 'prompt',
        icon: 'Sparkles',
        color: '#8b5cf6',
        isSystem: true,
        userId: null,
    },
    {
        id: 'type_3',
        name: 'command',
        icon: 'Terminal',
        color: '#f97316',
        isSystem: true,
        userId: null,
    },
    {
        id: 'type_4',
        name: 'note',
        icon: 'StickyNote',
        color: '#fde047',
        isSystem: true,
        userId: null,
    },
    {
        id: 'type_5',
        name: 'file',
        icon: 'File',
        color: '#6b7280',
        isSystem: true,
        userId: null,
    },
    {
        id: 'type_6',
        name: 'image',
        icon: 'Image',
        color: '#ec4899',
        isSystem: true,
        userId: null,
    },
    {
        id: 'type_7',
        name: 'link',
        icon: 'Link',
        color: '#10b981',
        isSystem: true,
        userId: null,
    },
];

export const mockCollections: Collection[] = [
    {
        id: 'coll_1',
        name: 'React Patterns',
        description: 'Common React patterns and hooks',
        isFavorite: true,
        itemCount: 12,
        userId: 'user_1',
        defaultTypeId: null,
        createdAt: new Date('2024-01-05'),
        updatedAt: new Date('2024-01-15'),
    },
    {
        id: 'coll_2',
        name: 'Python Snippets',
        description: 'Useful Python code snippets',
        isFavorite: false,
        itemCount: 8,
        userId: 'user_1',
        defaultTypeId: null,
        createdAt: new Date('2024-01-08'),
        updatedAt: new Date('2024-01-12'),
    },
    {
        id: 'coll_3',
        name: 'Context Files',
        description: 'AI context files for projects',
        isFavorite: true,
        itemCount: 5,
        userId: 'user_1',
        defaultTypeId: null,
        createdAt: new Date('2024-01-03'),
        updatedAt: new Date('2024-01-14'),
    },
    {
        id: 'coll_4',
        name: 'Interview Prep',
        description: 'Resources for interview preparation',
        isFavorite: false,
        itemCount: 34,
        userId: 'user_1',
        defaultTypeId: null,
        createdAt: new Date('2024-01-02'),
        updatedAt: new Date('2024-01-16'),
    },
    {
        id: 'coll_5',
        name: 'Git Commands',
        description: 'Commonly used git commands',
        isFavorite: true,
        itemCount: 7,
        userId: 'user_1',
        defaultTypeId: null,
        createdAt: new Date('2024-01-06'),
        updatedAt: new Date('2024-01-13'),
    },
    {
        id: 'coll_6',
        name: 'AI Prompts',
        description: 'Curated prompts for coding',
        isFavorite: false,
        itemCount: 6,
        userId: 'user_1',
        defaultTypeId: null,
        createdAt: new Date('2024-01-10'),
        updatedAt: new Date('2024-01-15'),
    },
];

const textItem = (overrides: Partial<Item> & Pick<Item, 'id' | 'title' | 'content' | 'itemTypeId' | 'tags' | 'createdAt'>): Item => ({
    contentType: 'TEXT',
    description: null,
    url: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    isFavorite: false,
    isPinned: false,
    language: null,
    userId: 'user_1',
    updatedAt: overrides.createdAt,
    ...overrides,
})

export const mockItems: Item[] = [
    textItem({ id: 'item_1', title: 'useAuth Hook', content: 'const useAuth = () => {\n  // Custom auth hook implementation\n}', description: 'Custom authentication hook for React applications', isFavorite: true, isPinned: true, language: 'typescript', itemTypeId: 'type_1', tags: ['react', 'auth', 'hooks'], createdAt: new Date('2024-01-15') }),
    textItem({ id: 'item_2', title: 'API Error Handling Pattern', content: 'try {\n  // API call\n} catch (error) {\n  // Handle error\n}', description: 'Fetch wrapper with exponential backoff retry logic', isFavorite: true, isPinned: true, language: 'typescript', itemTypeId: 'type_1', tags: ['api', 'error-handling'], createdAt: new Date('2024-01-14') }),
    textItem({ id: 'item_3', title: 'Code Review Prompt', content: 'Review this code for security and performance issues...', description: 'Prompt for AI code reviews', itemTypeId: 'type_2', tags: ['ai', 'code-review'], createdAt: new Date('2024-01-13') }),
    textItem({ id: 'item_4', title: 'git reset --hard HEAD~1', content: 'git reset --hard HEAD~1', description: 'Reset to previous commit (destructive)', language: 'bash', itemTypeId: 'type_3', tags: ['git', 'reset'], createdAt: new Date('2024-01-12') }),
    textItem({ id: 'item_5', title: 'useLocalStorage Hook', content: 'const useLocalStorage = (key, initialValue) => { ... }', description: 'Persistent state management with localStorage', language: 'typescript', itemTypeId: 'type_1', tags: ['react', 'hooks', 'storage'], createdAt: new Date('2024-01-11') }),
    textItem({ id: 'item_6', title: 'Docker Compose Up', content: 'docker-compose up -d --build', description: 'Start containers in detached mode with rebuild', isFavorite: true, language: 'bash', itemTypeId: 'type_3', tags: ['docker', 'devops'], createdAt: new Date('2024-01-10') }),
    textItem({ id: 'item_7', title: 'Explain Code Prompt', content: 'Explain this code step by step, highlighting key concepts...', description: 'AI prompt for code explanations', itemTypeId: 'type_2', tags: ['ai', 'learning'], createdAt: new Date('2024-01-09') }),
    textItem({ id: 'item_8', title: 'Meeting Notes Template', content: '# Meeting Notes\n\n## Date:\n## Attendees:\n## Agenda:\n## Action Items:', description: 'Markdown template for meeting notes', language: 'markdown', itemTypeId: 'type_4', tags: ['template', 'meetings'], createdAt: new Date('2024-01-08') }),
    textItem({ id: 'item_9', title: 'Prisma Migration Command', content: 'npx prisma migrate dev --name migration_name', description: 'Create and apply Prisma database migration', language: 'bash', itemTypeId: 'type_3', tags: ['prisma', 'database'], createdAt: new Date('2024-01-07') }),
    textItem({ id: 'item_10', title: 'React Query Setup', content: 'const queryClient = new QueryClient()', description: 'TanStack Query client configuration', language: 'typescript', itemTypeId: 'type_1', tags: ['react', 'data-fetching'], createdAt: new Date('2024-01-06') }),
    textItem({ id: 'item_11', title: 'GitHub Actions Workflow', content: 'name: CI\non: [push, pull_request]', description: 'Basic CI/CD workflow template', language: 'yaml', itemTypeId: 'type_1', tags: ['ci-cd', 'github'], createdAt: new Date('2024-01-05') }),
    {
        id: 'item_12',
        title: 'Tailwind CSS Resources',
        contentType: 'URL',
        content: null,
        url: 'https://tailwindcss.com/docs',
        fileUrl: null,
        fileName: null,
        fileSize: null,
        description: 'Official Tailwind CSS documentation',
        isFavorite: true,
        isPinned: false,
        language: null,
        itemTypeId: 'type_7',
        userId: 'user_1',
        tags: ['css', 'docs'],
        createdAt: new Date('2024-01-04'),
        updatedAt: new Date('2024-01-04'),
    },
];

const ADDED_AT = new Date('2024-01-01')

// Maps itemId -> collectionId memberships
export const mockItemCollections: ItemCollection[] = [
    { itemId: 'item_1', collectionId: 'coll_1', addedAt: ADDED_AT },
    { itemId: 'item_2', collectionId: 'coll_1', addedAt: ADDED_AT },
    { itemId: 'item_5', collectionId: 'coll_1', addedAt: ADDED_AT },
    { itemId: 'item_10', collectionId: 'coll_1', addedAt: ADDED_AT },
    { itemId: 'item_5', collectionId: 'coll_2', addedAt: ADDED_AT },
    { itemId: 'item_10', collectionId: 'coll_2', addedAt: ADDED_AT },
    { itemId: 'item_9', collectionId: 'coll_2', addedAt: ADDED_AT },
    { itemId: 'item_7', collectionId: 'coll_3', addedAt: ADDED_AT },
    { itemId: 'item_3', collectionId: 'coll_3', addedAt: ADDED_AT },
    { itemId: 'item_1', collectionId: 'coll_4', addedAt: ADDED_AT },
    { itemId: 'item_3', collectionId: 'coll_4', addedAt: ADDED_AT },
    { itemId: 'item_8', collectionId: 'coll_4', addedAt: ADDED_AT },
    { itemId: 'item_12', collectionId: 'coll_4', addedAt: ADDED_AT },
    { itemId: 'item_4', collectionId: 'coll_5', addedAt: ADDED_AT },
    { itemId: 'item_9', collectionId: 'coll_5', addedAt: ADDED_AT },
    { itemId: 'item_3', collectionId: 'coll_6', addedAt: ADDED_AT },
    { itemId: 'item_7', collectionId: 'coll_6', addedAt: ADDED_AT },
];

export const mockItemTypeCounts = {
    snippet: 24,
    prompt: 18,
    command: 15,
    note: 12,
    file: 5,
    image: 3,
    link: 8,
};