import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import tseslint from "typescript-eslint";
import vitest from "@vitest/eslint-plugin";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Type-aware linting for TypeScript sources covered by tsconfig.json.
    // `projectService` gives typescript-eslint real per-file type info, powering
    // no-floating-promises, no-misused-promises, await-thenable, the no-unsafe-*
    // family, etc.
    files: ["**/*.ts", "**/*.tsx", "**/*.mts"],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Coding standard: unused vars/imports are errors, not warnings
      // (next/typescript downgrades this to "warn").
      "@typescript-eslint/no-unused-vars": "error",
    },
  },
  {
    // scripts/** is excluded from tsconfig.json, so it has no type program —
    // turn off type-checked rules there to avoid "not found by project service".
    files: ["scripts/**/*.ts"],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    // Test-aware linting for Vitest specs (valid-expect, no-focused/-disabled tests,
    // correct hook usage, …). Type-checked rules stay on for tests too.
    files: ["**/*.test.ts"],
    ...vitest.configs.recommended,
  },
  // Non-default ignores (eslint-config-next already ignores .next, out, build,
  // next-env.d.ts, and node_modules).
  globalIgnores([
    "tmp/**",
    "coverage/**",
    "src/generated/**",
    // Generated by `npm run openapi:gen` (openapi-typescript) — never hand-edit or auto-fix.
    "src/types/openapi.ts",
    "**/.obsidian/**",
    "prisma.config.ts",
    "**/venv/**",
    "**/.venv/**",
  ]),
  {
    // Every AI mutation must route through `runAiMutation`/`useAiMutation` (src/hooks/use-ai-usage.ts)
    // so the AI usage meter refetches after a token is spent. A direct `api.POST('/ai/…')` or
    // `$api.useMutation('post', '/ai/…')` anywhere else bypasses that invalidation.
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.object.name='api'][callee.property.name='POST'] > Literal[value=/^\\/ai\\//]",
          message:
            "Call AI routes through runAiMutation/useAiMutation (src/hooks/use-ai-usage.ts), not api.POST('/ai/…') directly — otherwise the AI usage meter never refetches.",
        },
        {
          selector:
            "CallExpression[callee.object.name='$api'][callee.property.name='useMutation'] > Literal[value=/^\\/ai\\//]",
          message:
            "Call AI routes through runAiMutation/useAiMutation (src/hooks/use-ai-usage.ts), not a $api AI mutation directly — otherwise the AI usage meter never refetches.",
        },
      ],
    },
  },
  {
    // The wrapper itself is the one sanctioned place that calls `api.POST` for AI routes.
    files: ["src/hooks/use-ai-usage.ts"],
    rules: { "no-restricted-syntax": "off" },
  },
]);

export default eslintConfig;
