/**
 * GENERATED THEME PRESETS TYPES
 * This file is automatically generated. Do not edit manually.
 */

export const APP_THEMES = [
  'modern-minimal',
  't3-chat',
  'twitter',
  'mocha-mousse',
  'bubblegum',
  'doom-64',
  'catppuccin',
  'graphite',
  'perpetuity',
  'kodama-grove',
  'cosmic-night',
  'tangerine',
  'quantum-rose',
  'nature',
  'bold-tech',
  'elegant-luxury',
  'amber-minimal',
  'supabase',
  'neo-brutalism',
  'solar-dusk',
  'claymorphism',
  'cyberpunk',
  'pastel-dreams',
  'clean-slate',
  'caffeine',
  'ocean-breeze',
  'retro-arcade',
  'midnight-bloom',
  'candyland',
  'northern-lights',
  'vintage-paper',
  'sunset-horizon',
  'starry-night',
  'claude',
  'vercel',
  'mono',
  'violet-bloom',
  'amethyst-haze',
  'soft-pop',
  'sage-garden',
  'notebook',
  'darkmatter',
] as const;

export type AppTheme = typeof APP_THEMES[number];

export interface ThemePresetOption {
  value: AppTheme;
  label: string;
  description: string;
  light: {
    bg: string;
    primary: string;
  };
  dark: {
    bg: string;
    primary: string;
  };
}

export const APP_THEME_OPTIONS: ThemePresetOption[] = [
  {
    value: 'modern-minimal',
    label: 'Modern Minimal',
    description: 'A theme based on the Modern Minimal color palette.',
    light: {
      bg: 'oklch(1.00 0 0)',
      primary: 'oklch(0.62 0.19 259.81)',
    },
    dark: {
      bg: 'oklch(0.20 0 0)',
      primary: 'oklch(0.62 0.19 259.81)',
    },
  },
  {
    value: 't3-chat',
    label: 'T3 Chat',
    description: 'A theme based on the T3 Chat color palette.',
    light: {
      bg: 'oklch(0.98 0.01 325.64)',
      primary: 'oklch(0.53 0.14 355.20)',
    },
    dark: {
      bg: 'oklch(0.24 0.02 307.53)',
      primary: 'oklch(0.46 0.19 4.10)',
    },
  },
  {
    value: 'twitter',
    label: 'Twitter',
    description: 'A theme based on the Twitter color palette.',
    light: {
      bg: 'oklch(1.00 0 0)',
      primary: 'oklch(0.67 0.16 245.00)',
    },
    dark: {
      bg: 'oklch(0 0 0)',
      primary: 'oklch(0.67 0.16 245.01)',
    },
  },
  {
    value: 'mocha-mousse',
    label: 'Mocha Mousse',
    description: 'A theme based on the Mocha Mousse color palette.',
    light: {
      bg: 'oklch(0.95 0.01 102.46)',
      primary: 'oklch(0.61 0.06 44.36)',
    },
    dark: {
      bg: 'oklch(0.27 0.01 48.18)',
      primary: 'oklch(0.73 0.05 52.33)',
    },
  },
  {
    value: 'bubblegum',
    label: 'Bubblegum',
    description: 'A theme based on the Bubblegum color palette.',
    light: {
      bg: 'oklch(0.94 0.02 345.70)',
      primary: 'oklch(0.62 0.18 348.14)',
    },
    dark: {
      bg: 'oklch(0.25 0.03 234.16)',
      primary: 'oklch(0.92 0.08 87.67)',
    },
  },
  {
    value: 'doom-64',
    label: 'Doom 64',
    description: 'A theme based on the Doom 64 color palette.',
    light: {
      bg: 'oklch(0.85 0 0)',
      primary: 'oklch(0.50 0.19 27.48)',
    },
    dark: {
      bg: 'oklch(0.22 0 0)',
      primary: 'oklch(0.61 0.21 27.03)',
    },
  },
  {
    value: 'catppuccin',
    label: 'Catppuccin',
    description: 'A theme based on the Catppuccin color palette.',
    light: {
      bg: 'oklch(0.96 0.01 264.53)',
      primary: 'oklch(0.55 0.25 297.02)',
    },
    dark: {
      bg: 'oklch(0.22 0.03 284.06)',
      primary: 'oklch(0.79 0.12 304.77)',
    },
  },
  {
    value: 'graphite',
    label: 'Graphite',
    description: 'A theme based on the Graphite color palette.',
    light: {
      bg: 'oklch(0.96 0 0)',
      primary: 'oklch(0.49 0 0)',
    },
    dark: {
      bg: 'oklch(0.22 0 0)',
      primary: 'oklch(0.71 0 0)',
    },
  },
  {
    value: 'perpetuity',
    label: 'Perpetuity',
    description: 'A theme based on the Perpetuity color palette.',
    light: {
      bg: 'oklch(0.95 0.01 197.01)',
      primary: 'oklch(0.56 0.09 203.28)',
    },
    dark: {
      bg: 'oklch(0.21 0.02 224.45)',
      primary: 'oklch(0.85 0.13 195.04)',
    },
  },
  {
    value: 'kodama-grove',
    label: 'Kodama Grove',
    description: 'A theme based on the Kodama Grove color palette.',
    light: {
      bg: 'oklch(0.88 0.05 91.79)',
      primary: 'oklch(0.67 0.11 118.91)',
    },
    dark: {
      bg: 'oklch(0.33 0.02 88.07)',
      primary: 'oklch(0.68 0.06 132.45)',
    },
  },
  {
    value: 'cosmic-night',
    label: 'Cosmic Night',
    description: 'A theme based on the Cosmic Night color palette.',
    light: {
      bg: 'oklch(0.97 0.01 286.15)',
      primary: 'oklch(0.54 0.18 288.03)',
    },
    dark: {
      bg: 'oklch(0.17 0.02 283.80)',
      primary: 'oklch(0.72 0.16 290.40)',
    },
  },
  {
    value: 'tangerine',
    label: 'Tangerine',
    description: 'A theme based on the Tangerine color palette.',
    light: {
      bg: 'oklch(0.94 0.00 236.50)',
      primary: 'oklch(0.64 0.17 36.44)',
    },
    dark: {
      bg: 'oklch(0.26 0.03 262.67)',
      primary: 'oklch(0.64 0.17 36.44)',
    },
  },
  {
    value: 'quantum-rose',
    label: 'Quantum Rose',
    description: 'A theme based on the Quantum Rose color palette.',
    light: {
      bg: 'oklch(0.97 0.02 343.93)',
      primary: 'oklch(0.60 0.24 0.13)',
    },
    dark: {
      bg: 'oklch(0.18 0.05 313.72)',
      primary: 'oklch(0.75 0.23 332.02)',
    },
  },
  {
    value: 'nature',
    label: 'Nature',
    description: 'A theme based on the Nature color palette.',
    light: {
      bg: 'oklch(0.97 0.01 80.72)',
      primary: 'oklch(0.52 0.13 144.17)',
    },
    dark: {
      bg: 'oklch(0.27 0.03 150.77)',
      primary: 'oklch(0.67 0.16 144.21)',
    },
  },
  {
    value: 'bold-tech',
    label: 'Bold Tech',
    description: 'A theme based on the Bold Tech color palette.',
    light: {
      bg: 'oklch(1.00 0 0)',
      primary: 'oklch(0.61 0.22 292.72)',
    },
    dark: {
      bg: 'oklch(0.21 0.04 265.75)',
      primary: 'oklch(0.61 0.22 292.72)',
    },
  },
  {
    value: 'elegant-luxury',
    label: 'Elegant Luxury',
    description: 'A theme based on the Elegant Luxury color palette.',
    light: {
      bg: 'oklch(0.98 0.00 56.38)',
      primary: 'oklch(0.47 0.15 24.94)',
    },
    dark: {
      bg: 'oklch(0.22 0.01 56.04)',
      primary: 'oklch(0.51 0.19 27.52)',
    },
  },
  {
    value: 'amber-minimal',
    label: 'Amber Minimal',
    description: 'A theme based on the Amber Minimal color palette.',
    light: {
      bg: 'oklch(1.00 0 0)',
      primary: 'oklch(0.77 0.16 70.08)',
    },
    dark: {
      bg: 'oklch(0.20 0 0)',
      primary: 'oklch(0.77 0.16 70.08)',
    },
  },
  {
    value: 'supabase',
    label: 'Supabase',
    description: 'A theme based on the Supabase color palette.',
    light: {
      bg: 'oklch(0.99 0 0)',
      primary: 'oklch(0.83 0.13 160.91)',
    },
    dark: {
      bg: 'oklch(0.18 0 0)',
      primary: 'oklch(0.44 0.10 156.76)',
    },
  },
  {
    value: 'neo-brutalism',
    label: 'Neo Brutalism',
    description: 'A theme based on the Neo Brutalism color palette.',
    light: {
      bg: 'oklch(1.00 0 0)',
      primary: 'oklch(0.65 0.24 26.97)',
    },
    dark: {
      bg: 'oklch(0 0 0)',
      primary: 'oklch(0.70 0.19 23.19)',
    },
  },
  {
    value: 'solar-dusk',
    label: 'Solar Dusk',
    description: 'A theme based on the Solar Dusk color palette.',
    light: {
      bg: 'oklch(0.99 0.01 84.57)',
      primary: 'oklch(0.56 0.15 49.00)',
    },
    dark: {
      bg: 'oklch(0.22 0.01 56.04)',
      primary: 'oklch(0.70 0.19 47.60)',
    },
  },
  {
    value: 'claymorphism',
    label: 'Claymorphism',
    description: 'A theme based on the Claymorphism color palette.',
    light: {
      bg: 'oklch(0.92 0.00 48.72)',
      primary: 'oklch(0.59 0.20 277.12)',
    },
    dark: {
      bg: 'oklch(0.22 0.01 67.44)',
      primary: 'oklch(0.68 0.16 276.93)',
    },
  },
  {
    value: 'cyberpunk',
    label: 'Cyberpunk',
    description: 'A theme based on the Cyberpunk color palette.',
    light: {
      bg: 'oklch(0.98 0.00 247.84)',
      primary: 'oklch(0.67 0.29 341.41)',
    },
    dark: {
      bg: 'oklch(0.16 0.04 281.83)',
      primary: 'oklch(0.67 0.29 341.41)',
    },
  },
  {
    value: 'pastel-dreams',
    label: 'Pastel Dreams',
    description: 'A theme based on the Pastel Dreams color palette.',
    light: {
      bg: 'oklch(0.97 0.01 314.78)',
      primary: 'oklch(0.71 0.16 293.54)',
    },
    dark: {
      bg: 'oklch(0.22 0.01 56.04)',
      primary: 'oklch(0.79 0.12 295.75)',
    },
  },
  {
    value: 'clean-slate',
    label: 'Clean Slate',
    description: 'A theme based on the Clean Slate color palette.',
    light: {
      bg: 'oklch(0.98 0.00 247.86)',
      primary: 'oklch(0.59 0.20 277.12)',
    },
    dark: {
      bg: 'oklch(0.21 0.04 265.75)',
      primary: 'oklch(0.68 0.16 276.93)',
    },
  },
  {
    value: 'caffeine',
    label: 'Caffeine',
    description: 'A theme based on the Caffeine color palette.',
    light: {
      bg: 'oklch(0.98 0 0)',
      primary: 'oklch(0.43 0.04 41.99)',
    },
    dark: {
      bg: 'oklch(0.18 0 0)',
      primary: 'oklch(0.92 0.05 66.17)',
    },
  },
  {
    value: 'ocean-breeze',
    label: 'Ocean Breeze',
    description: 'A theme based on the Ocean Breeze color palette.',
    light: {
      bg: 'oklch(0.98 0.01 244.25)',
      primary: 'oklch(0.72 0.19 149.58)',
    },
    dark: {
      bg: 'oklch(0.21 0.04 265.75)',
      primary: 'oklch(0.77 0.15 163.22)',
    },
  },
  {
    value: 'retro-arcade',
    label: 'Retro Arcade',
    description: 'A theme based on the Retro Arcade color palette.',
    light: {
      bg: 'oklch(0.97 0.03 90.10)',
      primary: 'oklch(0.59 0.20 355.89)',
    },
    dark: {
      bg: 'oklch(0.27 0.05 219.82)',
      primary: 'oklch(0.59 0.20 355.89)',
    },
  },
  {
    value: 'midnight-bloom',
    label: 'Midnight Bloom',
    description: 'A theme based on the Midnight Bloom color palette.',
    light: {
      bg: 'oklch(0.98 0 0)',
      primary: 'oklch(0.57 0.20 283.08)',
    },
    dark: {
      bg: 'oklch(0.23 0.01 264.29)',
      primary: 'oklch(0.57 0.20 283.08)',
    },
  },
  {
    value: 'candyland',
    label: 'Candyland',
    description: 'A theme based on the Candyland color palette.',
    light: {
      bg: 'oklch(0.98 0.00 228.78)',
      primary: 'oklch(0.87 0.07 7.09)',
    },
    dark: {
      bg: 'oklch(0.23 0.01 264.29)',
      primary: 'oklch(0.80 0.14 349.23)',
    },
  },
  {
    value: 'northern-lights',
    label: 'Northern Lights',
    description: 'A theme based on the Northern Lights color palette.',
    light: {
      bg: 'oklch(0.98 0.00 286.38)',
      primary: 'oklch(0.65 0.15 150.31)',
    },
    dark: {
      bg: 'oklch(0.23 0.01 264.29)',
      primary: 'oklch(0.65 0.15 150.31)',
    },
  },
  {
    value: 'vintage-paper',
    label: 'Vintage Paper',
    description: 'A theme based on the Vintage Paper color palette.',
    light: {
      bg: 'oklch(0.96 0.02 90.24)',
      primary: 'oklch(0.62 0.08 65.54)',
    },
    dark: {
      bg: 'oklch(0.27 0.01 57.65)',
      primary: 'oklch(0.73 0.06 66.70)',
    },
  },
  {
    value: 'sunset-horizon',
    label: 'Sunset Horizon',
    description: 'A theme based on the Sunset Horizon color palette.',
    light: {
      bg: 'oklch(0.99 0.01 56.32)',
      primary: 'oklch(0.74 0.16 34.71)',
    },
    dark: {
      bg: 'oklch(0.26 0.02 352.40)',
      primary: 'oklch(0.74 0.16 34.71)',
    },
  },
  {
    value: 'starry-night',
    label: 'Starry Night',
    description: 'A theme based on the Starry Night color palette.',
    light: {
      bg: 'oklch(0.98 0.00 258.32)',
      primary: 'oklch(0.48 0.12 263.38)',
    },
    dark: {
      bg: 'oklch(0.22 0.02 275.84)',
      primary: 'oklch(0.48 0.12 263.38)',
    },
  },
  {
    value: 'claude',
    label: 'Claude',
    description: 'A theme based on the Claude color palette.',
    light: {
      bg: 'oklch(0.98 0.01 95.10)',
      primary: 'oklch(0.62 0.14 39.04)',
    },
    dark: {
      bg: 'oklch(0.27 0.00 106.64)',
      primary: 'oklch(0.67 0.13 38.76)',
    },
  },
  {
    value: 'vercel',
    label: 'Vercel',
    description: 'A theme based on the Vercel color palette.',
    light: {
      bg: 'oklch(0.99 0 0)',
      primary: 'oklch(0 0 0)',
    },
    dark: {
      bg: 'oklch(0 0 0)',
      primary: 'oklch(1 0 0)',
    },
  },
  {
    value: 'mono',
    label: 'Mono',
    description: 'A theme based on the Mono color palette.',
    light: {
      bg: 'oklch(1.00 0 0)',
      primary: 'oklch(0.56 0 0)',
    },
    dark: {
      bg: 'oklch(0.14 0 0)',
      primary: 'oklch(0.56 0 0)',
    },
  },
  {
    value: 'violet-bloom',
    label: 'Violet Bloom',
    description: '',
    light: {
      bg: 'oklch(0.9940 0 0)',
      primary: 'oklch(0.5393 0.2713 286.7462)',
    },
    dark: {
      bg: 'oklch(0.2223 0.0060 271.1393)',
      primary: 'oklch(0.6132 0.2294 291.7437)',
    },
  },
  {
    value: 'amethyst-haze',
    label: 'Amethyst Haze',
    description: '',
    light: {
      bg: 'oklch(0.9777 0.0041 301.4256)',
      primary: 'oklch(0.6104 0.0767 299.7335)',
    },
    dark: {
      bg: 'oklch(0.2166 0.0215 292.8474)',
      primary: 'oklch(0.7058 0.0777 302.0489)',
    },
  },
  {
    value: 'soft-pop',
    label: 'Soft Pop',
    description: '',
    light: {
      bg: 'oklch(0.9789 0.0082 121.6272)',
      primary: 'oklch(0.5106 0.2301 276.9656)',
    },
    dark: {
      bg: 'oklch(0 0 0)',
      primary: 'oklch(0.6801 0.1583 276.9349)',
    },
  },
  {
    value: 'sage-garden',
    label: 'Sage Garden',
    description: '',
    light: {
      bg: 'oklch(0.9761 0.0041 91.4461)',
      primary: 'oklch(0.6333 0.0309 154.9039)',
    },
    dark: {
      bg: 'oklch(0.1448 0 0)',
      primary: 'oklch(0.6333 0.0309 154.9039)',
    },
  },
  {
    value: 'notebook',
    label: 'Notebook',
    description: '',
    light: {
      bg: 'oklch(0.9821 0 0)',
      primary: 'oklch(0.4891 0 0)',
    },
    dark: {
      bg: 'oklch(0.2891 0 0)',
      primary: 'oklch(0.7572 0 0)',
    },
  },
  {
    value: 'darkmatter',
    label: 'Darkmatter',
    description: '',
    light: {
      bg: 'oklch(1.0000 0 0)',
      primary: 'oklch(0.6716 0.1368 48.5130)',
    },
    dark: {
      bg: 'oklch(0.1797 0.0043 308.1928)',
      primary: 'oklch(0.7214 0.1337 49.9802)',
    },
  },
];
