import fs from 'fs';
import path from 'path';

const rawPresetsPath = path.join(process.cwd(), 'src/lib/themes/presets-raw.json');
const rawPresets = JSON.parse(fs.readFileSync(rawPresetsPath, 'utf8'));

// Generate CSS
let cssContent = `/* ============================================================
 *  GENERATED THEME PRESETS CSS
 *  This file is automatically generated. Do not edit manually.
 * ============================================================ */

`;

// Generate baseline tokens for modern-minimal as root defaults (so pre-hydration / no-js looks correct)
const defaultPreset = rawPresets.find(p => p.slug === 'modern-minimal');

cssContent += `/* Default (Modern Minimal) Baseline */
:root {
  --radius: 0.625rem;
`;
for (const [key, value] of Object.entries(defaultPreset.light)) {
  cssContent += `  --${key}: ${value};\n`;
}
cssContent += `}\n\n.dark {\n`;
for (const [key, value] of Object.entries(defaultPreset.dark)) {
  cssContent += `  --${key}: ${value};\n`;
}
cssContent += `}\n\n`;

// Generate data-theme presets
for (const preset of rawPresets) {
  cssContent += `/* ${preset.name} Theme Preset */\n`;
  
  // Light block
  cssContent += `[data-theme="${preset.slug}"] {\n`;
  cssContent += `  color-scheme: light;\n`;
  for (const [key, value] of Object.entries(preset.light)) {
    cssContent += `  --${key}: ${value};\n`;
  }
  cssContent += `}\n\n`;

  // Dark block
  cssContent += `.dark[data-theme="${preset.slug}"], .dark [data-theme="${preset.slug}"] {\n`;
  cssContent += `  color-scheme: dark;\n`;
  for (const [key, value] of Object.entries(preset.dark)) {
    cssContent += `  --${key}: ${value};\n`;
  }
  cssContent += `}\n\n`;
}

const cssOutputPath = path.join(process.cwd(), 'src/app/themes.generated.css');
fs.writeFileSync(cssOutputPath, cssContent, 'utf8');
console.log(`Generated CSS at: ${cssOutputPath}`);

// Generate TypeScript definitions
let tsContent = `/**
 * GENERATED THEME PRESETS TYPES
 * This file is automatically generated. Do not edit manually.
 */

export const APP_THEMES = [
`;
for (const preset of rawPresets) {
  tsContent += `  '${preset.slug}',\n`;
}
tsContent += `] as const;\n\nexport type AppTheme = typeof APP_THEMES[number];\n\n`;

tsContent += `export interface ThemePresetOption {
  value: AppTheme;
  label: string;
  description: string;
  light: {
    bg: string;
    primary: string;
  };
  dark: {
    bg: string;
    primary: string;
  };
}

export const APP_THEME_OPTIONS: ThemePresetOption[] = [
`;
for (const preset of rawPresets) {
  tsContent += `  {\n`;
  tsContent += `    value: '${preset.slug}',\n`;
  tsContent += `    label: '${preset.name}',\n`;
  tsContent += `    description: '${preset.description}',\n`;
  tsContent += `    light: {\n`;
  tsContent += `      bg: '${preset.light.background}',\n`;
  tsContent += `      primary: '${preset.light.primary}',\n`;
  tsContent += `    },\n`;
  tsContent += `    dark: {\n`;
  tsContent += `      bg: '${preset.dark.background}',\n`;
  tsContent += `      primary: '${preset.dark.primary}',\n`;
  tsContent += `    },\n`;
  tsContent += `  },\n`;
}
tsContent += `];\n`;

const tsOutputPath = path.join(process.cwd(), 'src/types/theme-presets.generated.ts');
fs.writeFileSync(tsOutputPath, tsContent, 'utf8');
console.log(`Generated TypeScript types at: ${tsOutputPath}`);
