// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AuthConfirmLoginEmailData,
  AuthConfirmLoginEmailErrors,
  AuthConfirmLoginEmailResponses,
  AuthForgotPasswordData,
  AuthForgotPasswordErrors,
  AuthForgotPasswordResponses,
  AuthLoginData,
  AuthLoginErrors,
  AuthLoginResponses,
  AuthLogoutData,
  AuthLogoutErrors,
  AuthLogoutResponses,
  AuthOauthGithubCallbackData,
  AuthOauthGithubCallbackErrors,
  AuthOauthGithubCallbackResponses,
  AuthOauthGithubStartData,
  AuthOauthGithubStartErrors,
  AuthOauthGithubStartResponses,
  AuthOauthGoogleCallbackData,
  AuthOauthGoogleCallbackErrors,
  AuthOauthGoogleCallbackResponses,
  AuthOauthGoogleStartData,
  AuthOauthGoogleStartErrors,
  AuthOauthGoogleStartResponses,
  AuthOauthLinkData,
  AuthOauthLinkErrors,
  AuthOauthLinkResponses,
  AuthRegisterData,
  AuthRegisterErrors,
  AuthRegisterResponses,
  AuthResendVerificationData,
  AuthResendVerificationErrors,
  AuthResendVerificationResponses,
  AuthResetPasswordData,
  AuthResetPasswordErrors,
  AuthResetPasswordResponses,
  AuthSessionData,
  AuthSessionErrors,
  AuthSessionResponses,
  AuthVerifyEmailData,
  AuthVerifyEmailErrors,
  AuthVerifyEmailResponses,
  CreateCollectionData,
  CreateCollectionErrors,
  CreateCollectionResponses,
  CreateItemData,
  CreateItemErrors,
  CreateItemResponses,
  CspReportData,
  CspReportErrors,
  CspReportResponses,
  DeleteAccountData,
  DeleteAccountErrors,
  DeleteAccountResponses,
  DeleteCollectionData,
  DeleteCollectionErrors,
  DeleteCollectionResponses,
  DeleteItemData,
  DeleteItemErrors,
  DeleteItemResponses,
  GetActivityData,
  GetActivityErrors,
  GetActivityResponses,
  GetCollectionData,
  GetCollectionErrors,
  GetCollectionResponses,
  GetHealthData,
  GetHealthErrors,
  GetHealthResponses,
  GetItemContentData,
  GetItemContentErrors,
  GetItemContentResponses,
  GetItemData,
  GetItemDetailsData,
  GetItemDetailsErrors,
  GetItemDetailsResponses,
  GetItemErrors,
  GetItemResponses,
  GetPreferencesData,
  GetPreferencesErrors,
  GetPreferencesResponses,
  GetReadinessData,
  GetReadinessErrors,
  GetReadinessResponses,
  GetStatsData,
  GetStatsErrors,
  GetStatsResponses,
  GlobalSearchData,
  GlobalSearchErrors,
  GlobalSearchResponses,
  ListCollectionsData,
  ListCollectionsErrors,
  ListCollectionsResponses,
  ListItemsData,
  ListItemsErrors,
  ListItemsResponses,
  SetCollectionFavoriteData,
  SetCollectionFavoriteErrors,
  SetCollectionFavoriteResponses,
  SetItemFavoriteData,
  SetItemFavoriteErrors,
  SetItemFavoriteResponses,
  SetItemPinnedData,
  SetItemPinnedErrors,
  SetItemPinnedResponses,
  UpdateCollectionData,
  UpdateCollectionErrors,
  UpdateCollectionResponses,
  UpdateItemData,
  UpdateItemErrors,
  UpdateItemResponses,
  UpdatePreferencesData,
  UpdatePreferencesErrors,
  UpdatePreferencesResponses,
  UpdateProfileData,
  UpdateProfileErrors,
  UpdateProfileResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Confirm a credential sign-in email
 */
export const authConfirmLoginEmail = <ThrowOnError extends boolean = false>(
  options: Options<AuthConfirmLoginEmailData, ThrowOnError>,
): RequestResult<
  AuthConfirmLoginEmailResponses,
  AuthConfirmLoginEmailErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthConfirmLoginEmailResponses,
    AuthConfirmLoginEmailErrors,
    ThrowOnError
  >({
    url: "/auth/confirm-login-email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Request a password reset link
 */
export const authForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthForgotPasswordData, ThrowOnError>,
): RequestResult<
  AuthForgotPasswordResponses,
  AuthForgotPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthForgotPasswordResponses,
    AuthForgotPasswordErrors,
    ThrowOnError
  >({
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Confirm and link a pending OAuth account with a password
 */
export const authOauthLink = <ThrowOnError extends boolean = false>(
  options: Options<AuthOauthLinkData, ThrowOnError>,
): RequestResult<AuthOauthLinkResponses, AuthOauthLinkErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthOauthLinkResponses,
    AuthOauthLinkErrors,
    ThrowOnError
  >({
    url: "/auth/link",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Log in with email and password
 */
export const authLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginData, ThrowOnError>,
): RequestResult<AuthLoginResponses, AuthLoginErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthLoginResponses,
    AuthLoginErrors,
    ThrowOnError
  >({
    url: "/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Log out of the current session
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthLogoutData, ThrowOnError>,
): RequestResult<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    AuthLogoutResponses,
    AuthLogoutErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/auth/logout",
    ...options,
  });

/**
 * Complete github OAuth sign-in
 */
export const authOauthGithubCallback = <ThrowOnError extends boolean = false>(
  options?: Options<AuthOauthGithubCallbackData, ThrowOnError>,
): RequestResult<
  AuthOauthGithubCallbackResponses,
  AuthOauthGithubCallbackErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AuthOauthGithubCallbackResponses,
    AuthOauthGithubCallbackErrors,
    ThrowOnError
  >({ url: "/auth/oauth/github/callback", ...options });

/**
 * Begin github OAuth sign-in
 */
export const authOauthGithubStart = <ThrowOnError extends boolean = false>(
  options?: Options<AuthOauthGithubStartData, ThrowOnError>,
): RequestResult<
  AuthOauthGithubStartResponses,
  AuthOauthGithubStartErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AuthOauthGithubStartResponses,
    AuthOauthGithubStartErrors,
    ThrowOnError
  >({ url: "/auth/oauth/github/start", ...options });

/**
 * Complete google OAuth sign-in
 */
export const authOauthGoogleCallback = <ThrowOnError extends boolean = false>(
  options?: Options<AuthOauthGoogleCallbackData, ThrowOnError>,
): RequestResult<
  AuthOauthGoogleCallbackResponses,
  AuthOauthGoogleCallbackErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AuthOauthGoogleCallbackResponses,
    AuthOauthGoogleCallbackErrors,
    ThrowOnError
  >({ url: "/auth/oauth/google/callback", ...options });

/**
 * Begin google OAuth sign-in
 */
export const authOauthGoogleStart = <ThrowOnError extends boolean = false>(
  options?: Options<AuthOauthGoogleStartData, ThrowOnError>,
): RequestResult<
  AuthOauthGoogleStartResponses,
  AuthOauthGoogleStartErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    AuthOauthGoogleStartResponses,
    AuthOauthGoogleStartErrors,
    ThrowOnError
  >({ url: "/auth/oauth/google/start", ...options });

/**
 * Register a new account
 */
export const authRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthRegisterData, ThrowOnError>,
): RequestResult<AuthRegisterResponses, AuthRegisterErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthRegisterResponses,
    AuthRegisterErrors,
    ThrowOnError
  >({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Resend the email verification link
 */
export const authResendVerification = <ThrowOnError extends boolean = false>(
  options: Options<AuthResendVerificationData, ThrowOnError>,
): RequestResult<
  AuthResendVerificationResponses,
  AuthResendVerificationErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthResendVerificationResponses,
    AuthResendVerificationErrors,
    ThrowOnError
  >({
    url: "/auth/resend-verification",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset a password with a token
 */
export const authResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthResetPasswordData, ThrowOnError>,
): RequestResult<
  AuthResetPasswordResponses,
  AuthResetPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthResetPasswordResponses,
    AuthResetPasswordErrors,
    ThrowOnError
  >({
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get the current session user
 */
export const authSession = <ThrowOnError extends boolean = false>(
  options?: Options<AuthSessionData, ThrowOnError>,
): RequestResult<AuthSessionResponses, AuthSessionErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    AuthSessionResponses,
    AuthSessionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/auth/session",
    ...options,
  });

/**
 * Confirm an email verification token
 */
export const authVerifyEmail = <ThrowOnError extends boolean = false>(
  options: Options<AuthVerifyEmailData, ThrowOnError>,
): RequestResult<
  AuthVerifyEmailResponses,
  AuthVerifyEmailErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AuthVerifyEmailResponses,
    AuthVerifyEmailErrors,
    ThrowOnError
  >({
    url: "/auth/verify-email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all collections
 */
export const listCollections = <ThrowOnError extends boolean = false>(
  options?: Options<ListCollectionsData, ThrowOnError>,
): RequestResult<
  ListCollectionsResponses,
  ListCollectionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListCollectionsResponses,
    ListCollectionsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/collections",
    ...options,
  });

/**
 * Create a collection
 */
export const createCollection = <ThrowOnError extends boolean = false>(
  options: Options<CreateCollectionData, ThrowOnError>,
): RequestResult<
  CreateCollectionResponses,
  CreateCollectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCollectionResponses,
    CreateCollectionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/collections",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a collection
 */
export const deleteCollection = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCollectionData, ThrowOnError>,
): RequestResult<
  DeleteCollectionResponses,
  DeleteCollectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCollectionResponses,
    DeleteCollectionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/collections/{id}",
    ...options,
  });

/**
 * Get a single collection
 */
export const getCollection = <ThrowOnError extends boolean = false>(
  options: Options<GetCollectionData, ThrowOnError>,
): RequestResult<GetCollectionResponses, GetCollectionErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetCollectionResponses,
    GetCollectionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/collections/{id}",
    ...options,
  });

/**
 * Update a collection
 */
export const updateCollection = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCollectionData, ThrowOnError>,
): RequestResult<
  UpdateCollectionResponses,
  UpdateCollectionErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateCollectionResponses,
    UpdateCollectionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/collections/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Toggle a collection's favorite flag
 */
export const setCollectionFavorite = <ThrowOnError extends boolean = false>(
  options: Options<SetCollectionFavoriteData, ThrowOnError>,
): RequestResult<
  SetCollectionFavoriteResponses,
  SetCollectionFavoriteErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    SetCollectionFavoriteResponses,
    SetCollectionFavoriteErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/collections/{id}/favorite",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Ingest CSP violation reports
 *
 * Best-effort sink for browser Content-Security-Policy violation reports (Reporting API `report-to`). Rate-limited per IP; logs and discards; never reads a session or the database.
 */
export const cspReport = <ThrowOnError extends boolean = false>(
  options: Options<CspReportData, ThrowOnError>,
): RequestResult<CspReportResponses, CspReportErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CspReportResponses,
    CspReportErrors,
    ThrowOnError
  >({
    bodySerializer: null,
    url: "/csp-report",
    ...options,
    headers: {
      "Content-Type": "application/reports+json",
      ...options.headers,
    },
  });

/**
 * Liveness check
 */
export const getHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthData, ThrowOnError>,
): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetHealthResponses,
    GetHealthErrors,
    ThrowOnError
  >({ url: "/health", ...options });

/**
 * List items (recent, by type, by collection, or favorites)
 */
export const listItems = <ThrowOnError extends boolean = false>(
  options: Options<ListItemsData, ThrowOnError>,
): RequestResult<ListItemsResponses, ListItemsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ListItemsResponses,
    ListItemsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/items",
    ...options,
  });

/**
 * Create an item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemData, ThrowOnError>,
): RequestResult<CreateItemResponses, CreateItemErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateItemResponses,
    CreateItemErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete an item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: Options<DeleteItemData, ThrowOnError>,
): RequestResult<DeleteItemResponses, DeleteItemErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteItemResponses,
    DeleteItemErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/items/{id}",
    ...options,
  });

/**
 * Get a single item
 */
export const getItem = <ThrowOnError extends boolean = false>(
  options: Options<GetItemData, ThrowOnError>,
): RequestResult<GetItemResponses, GetItemErrors, ThrowOnError> =>
  (options.client ?? client).get<GetItemResponses, GetItemErrors, ThrowOnError>(
    {
      security: [
        {
          in: "cookie",
          name: "devstash_session",
          type: "apiKey",
        },
      ],
      url: "/items/{id}",
      ...options,
    },
  );

/**
 * Update an item
 */
export const updateItem = <ThrowOnError extends boolean = false>(
  options: Options<UpdateItemData, ThrowOnError>,
): RequestResult<UpdateItemResponses, UpdateItemErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    UpdateItemResponses,
    UpdateItemErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/items/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get an item's content
 */
export const getItemContent = <ThrowOnError extends boolean = false>(
  options: Options<GetItemContentData, ThrowOnError>,
): RequestResult<GetItemContentResponses, GetItemContentErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetItemContentResponses,
    GetItemContentErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/items/{id}/content",
    ...options,
  });

/**
 * Get an item's details
 */
export const getItemDetails = <ThrowOnError extends boolean = false>(
  options: Options<GetItemDetailsData, ThrowOnError>,
): RequestResult<GetItemDetailsResponses, GetItemDetailsErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetItemDetailsResponses,
    GetItemDetailsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/items/{id}/details",
    ...options,
  });

/**
 * Toggle an item's favorite flag
 */
export const setItemFavorite = <ThrowOnError extends boolean = false>(
  options: Options<SetItemFavoriteData, ThrowOnError>,
): RequestResult<
  SetItemFavoriteResponses,
  SetItemFavoriteErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    SetItemFavoriteResponses,
    SetItemFavoriteErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/items/{id}/favorite",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Toggle an item's pinned flag
 */
export const setItemPinned = <ThrowOnError extends boolean = false>(
  options: Options<SetItemPinnedData, ThrowOnError>,
): RequestResult<SetItemPinnedResponses, SetItemPinnedErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    SetItemPinnedResponses,
    SetItemPinnedErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/items/{id}/pinned",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete the current user's account
 */
export const deleteAccount = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteAccountData, ThrowOnError>,
): RequestResult<DeleteAccountResponses, DeleteAccountErrors, ThrowOnError> =>
  (options?.client ?? client).delete<
    DeleteAccountResponses,
    DeleteAccountErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/me",
    ...options,
  });

/**
 * Get the current user's editor preferences
 */
export const getPreferences = <ThrowOnError extends boolean = false>(
  options?: Options<GetPreferencesData, ThrowOnError>,
): RequestResult<GetPreferencesResponses, GetPreferencesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetPreferencesResponses,
    GetPreferencesErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/me/preferences",
    ...options,
  });

/**
 * Update the current user's editor preferences
 */
export const updatePreferences = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePreferencesData, ThrowOnError>,
): RequestResult<
  UpdatePreferencesResponses,
  UpdatePreferencesErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdatePreferencesResponses,
    UpdatePreferencesErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/me/preferences",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update the current user's profile
 */
export const updateProfile = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProfileData, ThrowOnError>,
): RequestResult<UpdateProfileResponses, UpdateProfileErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    UpdateProfileResponses,
    UpdateProfileErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/me/profile",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Readiness check
 */
export const getReadiness = <ThrowOnError extends boolean = false>(
  options?: Options<GetReadinessData, ThrowOnError>,
): RequestResult<GetReadinessResponses, GetReadinessErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetReadinessResponses,
    GetReadinessErrors,
    ThrowOnError
  >({ url: "/readyz", ...options });

/**
 * Search items and collections
 */
export const globalSearch = <ThrowOnError extends boolean = false>(
  options: Options<GlobalSearchData, ThrowOnError>,
): RequestResult<GlobalSearchResponses, GlobalSearchErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GlobalSearchResponses,
    GlobalSearchErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/search",
    ...options,
  });

/**
 * Get the current user's dashboard stats
 */
export const getStats = <ThrowOnError extends boolean = false>(
  options?: Options<GetStatsData, ThrowOnError>,
): RequestResult<GetStatsResponses, GetStatsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetStatsResponses,
    GetStatsErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/stats",
    ...options,
  });

/**
 * Get the current user's per-day item-creation activity
 */
export const getActivity = <ThrowOnError extends boolean = false>(
  options?: Options<GetActivityData, ThrowOnError>,
): RequestResult<GetActivityResponses, GetActivityErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetActivityResponses,
    GetActivityErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "devstash_session",
        type: "apiKey",
      },
    ],
    url: "/stats/activity",
    ...options,
  });
