// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.devstash.one" | "http://localhost:8080" | (string & {});
};

export type ActivityDay = {
  count: number;
  date: string;
  level: number;
};

export type ActivityOutputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  days: Array<ActivityDay> | null;
};

export type CollectionRef = {
  id: string;
  name: string;
};

export type CollectionWithTypes = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  createdAt: string;
  description: string | null;
  dominantColor: string | null;
  id: string;
  isFavorite: boolean;
  itemCount: number;
  name: string;
  types: Array<ItemType> | null;
};

export type ConfirmLoginEmailInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Repeat password
   */
  confirmPassword?: string;
  /**
   * Password (required only when adding sign-in)
   */
  password?: string;
  /**
   * Confirmation token from the email link
   */
  token: string;
};

export type CreateCollectionInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  description?: string;
  name: string;
};

export type CreateItemInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  collectionIds?: Array<string> | null;
  content?: string;
  description?: string;
  fileUrl?: string;
  imageHeight?: number;
  imageWidth?: number;
  itemTypeName: string;
  language?: string;
  tags?: Array<string> | null;
  title: string;
  url?: string;
};

export type EditorPreferences = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  appTheme: string;
  colorMode: string;
  editorThemeMode: string;
  fontSize: number;
  minimap: boolean;
  sidebarCollapsed: boolean;
  tabSize: number;
  uiSkin: string;
  wordWrap: string;
};

export type ErrorDetail = {
  /**
   * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
   */
  location?: string;
  /**
   * Error message text
   */
  message?: string;
  /**
   * The value at the given location
   */
  value?: unknown;
};

export type ErrorModel = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type FavoriteInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  isFavorite: boolean;
};

export type ForgotPasswordInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Account email
   */
  email: string;
};

export type FullItem = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  collections: Array<CollectionRef> | null;
  content: string | null;
  contentPreview: string | null;
  createdAt: string;
  description: string | null;
  descriptionPreview: string | null;
  fileName: string | null;
  fileSize: number | null;
  id: string;
  isFavorite: boolean;
  isPinned: boolean;
  itemType: SlimItemType;
  language: string | null;
  tags: Array<string> | null;
  title: string;
  updatedAt: string;
  url: string | null;
};

export type HealthOutputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  status: string;
};

export type ItemContent = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  content: string | null;
  language: string | null;
};

export type ItemDetails = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  collections: Array<CollectionRef> | null;
  description: string | null;
  updatedAt: string;
};

export type ItemSavedDetails = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  collections: Array<CollectionRef> | null;
  description: string | null;
  isFavorite: boolean;
  isPinned: boolean;
  tags: Array<string> | null;
  updatedAt: string;
  url: string | null;
};

export type ItemType = {
  color: string;
  icon: string;
  id: string;
  isSystem: boolean;
  name: string;
};

export type ItemTypeCount = {
  count: number;
  name: string;
};

export type ItemsPage = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Whether another page follows
   */
  hasMore: boolean;
  /**
   * The requested page of items
   */
  items: Array<LightItem> | null;
  /**
   * Cursor for the next page, if any
   */
  nextCursor: string | null;
  /**
   * Total items matching the filter
   */
  total: number;
};

export type LightItem = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  contentPreview: string | null;
  createdAt: string;
  descriptionPreview: string | null;
  fileName: string | null;
  fileSize: number | null;
  id: string;
  isFavorite: boolean;
  isPinned: boolean;
  itemType: SlimItemType;
  tags: Array<string> | null;
  title: string;
  url: string | null;
};

export type LoginInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Account email
   */
  email: string;
  /**
   * Account password
   */
  password: string;
};

export type OauthLinkInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Account password
   */
  password: string;
  /**
   * Pending-link token from the callback redirect
   */
  token: string;
};

export type PinnedInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  isPinned: boolean;
};

export type ProfileOutputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  image: string | null;
  name: string | null;
};

export type RedirectOutputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  redirectTo: string;
};

export type RegisterInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Repeat password
   */
  confirmPassword: string;
  /**
   * Account email
   */
  email: string;
  /**
   * Display name
   */
  name: string;
  /**
   * Account password
   */
  password: string;
};

export type ResendVerificationInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Account email
   */
  email: string;
};

export type ResetPasswordInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Repeat new password
   */
  confirmPassword: string;
  /**
   * New password
   */
  password: string;
  /**
   * Reset token from the email link
   */
  token: string;
};

export type SearchResult = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  collections: Array<SidebarCollection> | null;
  items: Array<LightItem> | null;
};

export type SessionOutputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  expires: string;
  user: SessionUser;
};

export type SessionUser = {
  email: string;
  id: string;
  image: string | null;
  isPro: boolean;
  name: string | null;
};

export type SidebarCollection = {
  description: string | null;
  dominantColor: string | null;
  id: string;
  isFavorite: boolean;
  itemCount: number;
  name: string;
};

export type SlimItemType = {
  name: string;
};

export type StatsOutputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  favoriteCollections: number;
  favoriteItems: number;
  itemTypeCounts: Array<ItemTypeCount> | null;
  totalCollections: number;
  totalItems: number;
};

export type UpdateCollectionInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  description?: string;
  isFavorite?: boolean;
  name?: string;
};

export type UpdateItemInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  collectionIds?: Array<string> | null;
  content?: string;
  description?: string;
  itemTypeName?: "snippet" | "prompt" | "command" | "note";
  language?: string;
  tags?: Array<string> | null;
  title: string;
  url?: string;
};

export type UpdatePreferencesInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  appTheme?: string;
  colorMode?: string;
  editorThemeMode?: string;
  fontSize?: number;
  minimap?: boolean;
  sidebarCollapsed?: boolean;
  tabSize?: number;
  uiSkin?: string;
  wordWrap?: string;
};

export type UpdateProfileInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Display name; null or empty clears it
   */
  name: string | null;
};

export type VerifyEmailInputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Verification token from the email link
   */
  token: string;
};

export type ActivityOutputBodyWritable = {
  days: Array<ActivityDay> | null;
};

export type CollectionWithTypesWritable = {
  createdAt: string;
  description: string | null;
  dominantColor: string | null;
  id: string;
  isFavorite: boolean;
  itemCount: number;
  name: string;
  types: Array<ItemType> | null;
};

export type ConfirmLoginEmailInputBodyWritable = {
  /**
   * Repeat password
   */
  confirmPassword?: string;
  /**
   * Password (required only when adding sign-in)
   */
  password?: string;
  /**
   * Confirmation token from the email link
   */
  token: string;
};

export type CreateCollectionInputBodyWritable = {
  description?: string;
  name: string;
};

export type CreateItemInputBodyWritable = {
  collectionIds?: Array<string> | null;
  content?: string;
  description?: string;
  fileUrl?: string;
  imageHeight?: number;
  imageWidth?: number;
  itemTypeName: string;
  language?: string;
  tags?: Array<string> | null;
  title: string;
  url?: string;
};

export type EditorPreferencesWritable = {
  appTheme: string;
  colorMode: string;
  editorThemeMode: string;
  fontSize: number;
  minimap: boolean;
  sidebarCollapsed: boolean;
  tabSize: number;
  uiSkin: string;
  wordWrap: string;
};

export type ErrorModelWritable = {
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type FavoriteInputBodyWritable = {
  isFavorite: boolean;
};

export type ForgotPasswordInputBodyWritable = {
  /**
   * Account email
   */
  email: string;
};

export type FullItemWritable = {
  collections: Array<CollectionRef> | null;
  content: string | null;
  contentPreview: string | null;
  createdAt: string;
  description: string | null;
  descriptionPreview: string | null;
  fileName: string | null;
  fileSize: number | null;
  id: string;
  isFavorite: boolean;
  isPinned: boolean;
  itemType: SlimItemType;
  language: string | null;
  tags: Array<string> | null;
  title: string;
  updatedAt: string;
  url: string | null;
};

export type HealthOutputBodyWritable = {
  status: string;
};

export type ItemContentWritable = {
  content: string | null;
  language: string | null;
};

export type ItemDetailsWritable = {
  collections: Array<CollectionRef> | null;
  description: string | null;
  updatedAt: string;
};

export type ItemSavedDetailsWritable = {
  collections: Array<CollectionRef> | null;
  description: string | null;
  isFavorite: boolean;
  isPinned: boolean;
  tags: Array<string> | null;
  updatedAt: string;
  url: string | null;
};

export type ItemsPageWritable = {
  /**
   * Whether another page follows
   */
  hasMore: boolean;
  /**
   * The requested page of items
   */
  items: Array<LightItemWritable> | null;
  /**
   * Cursor for the next page, if any
   */
  nextCursor: string | null;
  /**
   * Total items matching the filter
   */
  total: number;
};

export type LightItemWritable = {
  contentPreview: string | null;
  createdAt: string;
  descriptionPreview: string | null;
  fileName: string | null;
  fileSize: number | null;
  id: string;
  isFavorite: boolean;
  isPinned: boolean;
  itemType: SlimItemType;
  tags: Array<string> | null;
  title: string;
  url: string | null;
};

export type LoginInputBodyWritable = {
  /**
   * Account email
   */
  email: string;
  /**
   * Account password
   */
  password: string;
};

export type OauthLinkInputBodyWritable = {
  /**
   * Account password
   */
  password: string;
  /**
   * Pending-link token from the callback redirect
   */
  token: string;
};

export type PinnedInputBodyWritable = {
  isPinned: boolean;
};

export type ProfileOutputBodyWritable = {
  image: string | null;
  name: string | null;
};

export type RedirectOutputBodyWritable = {
  redirectTo: string;
};

export type RegisterInputBodyWritable = {
  /**
   * Repeat password
   */
  confirmPassword: string;
  /**
   * Account email
   */
  email: string;
  /**
   * Display name
   */
  name: string;
  /**
   * Account password
   */
  password: string;
};

export type ResendVerificationInputBodyWritable = {
  /**
   * Account email
   */
  email: string;
};

export type ResetPasswordInputBodyWritable = {
  /**
   * Repeat new password
   */
  confirmPassword: string;
  /**
   * New password
   */
  password: string;
  /**
   * Reset token from the email link
   */
  token: string;
};

export type SearchResultWritable = {
  collections: Array<SidebarCollection> | null;
  items: Array<LightItemWritable> | null;
};

export type SessionOutputBodyWritable = {
  expires: string;
  user: SessionUser;
};

export type StatsOutputBodyWritable = {
  favoriteCollections: number;
  favoriteItems: number;
  itemTypeCounts: Array<ItemTypeCount> | null;
  totalCollections: number;
  totalItems: number;
};

export type UpdateCollectionInputBodyWritable = {
  description?: string;
  isFavorite?: boolean;
  name?: string;
};

export type UpdateItemInputBodyWritable = {
  collectionIds?: Array<string> | null;
  content?: string;
  description?: string;
  itemTypeName?: "snippet" | "prompt" | "command" | "note";
  language?: string;
  tags?: Array<string> | null;
  title: string;
  url?: string;
};

export type UpdatePreferencesInputBodyWritable = {
  appTheme?: string;
  colorMode?: string;
  editorThemeMode?: string;
  fontSize?: number;
  minimap?: boolean;
  sidebarCollapsed?: boolean;
  tabSize?: number;
  uiSkin?: string;
  wordWrap?: string;
};

export type UpdateProfileInputBodyWritable = {
  /**
   * Display name; null or empty clears it
   */
  name: string | null;
};

export type VerifyEmailInputBodyWritable = {
  /**
   * Verification token from the email link
   */
  token: string;
};

export type AuthConfirmLoginEmailData = {
  body: ConfirmLoginEmailInputBodyWritable;
  path?: never;
  query?: never;
  url: "/auth/confirm-login-email";
};

export type AuthConfirmLoginEmailErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthConfirmLoginEmailError =
  AuthConfirmLoginEmailErrors[keyof AuthConfirmLoginEmailErrors];

export type AuthConfirmLoginEmailResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthConfirmLoginEmailResponse =
  AuthConfirmLoginEmailResponses[keyof AuthConfirmLoginEmailResponses];

export type AuthForgotPasswordData = {
  body: ForgotPasswordInputBodyWritable;
  path?: never;
  query?: never;
  url: "/auth/forgot-password";
};

export type AuthForgotPasswordErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthForgotPasswordError =
  AuthForgotPasswordErrors[keyof AuthForgotPasswordErrors];

export type AuthForgotPasswordResponses = {
  /**
   * OK
   */
  200: RedirectOutputBody;
};

export type AuthForgotPasswordResponse =
  AuthForgotPasswordResponses[keyof AuthForgotPasswordResponses];

export type AuthOauthLinkData = {
  body: OauthLinkInputBodyWritable;
  path?: never;
  query?: never;
  url: "/auth/link";
};

export type AuthOauthLinkErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthOauthLinkError = AuthOauthLinkErrors[keyof AuthOauthLinkErrors];

export type AuthOauthLinkResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthOauthLinkResponse =
  AuthOauthLinkResponses[keyof AuthOauthLinkResponses];

export type AuthLoginData = {
  body: LoginInputBodyWritable;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type AuthLoginErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/logout";
};

export type AuthLogoutErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthLogoutError = AuthLogoutErrors[keyof AuthLogoutErrors];

export type AuthLogoutResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthOauthGithubCallbackData = {
  body?: never;
  path?: never;
  query?: {
    code?: string;
    state?: string;
    error?: string;
  };
  url: "/auth/oauth/github/callback";
};

export type AuthOauthGithubCallbackErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthOauthGithubCallbackError =
  AuthOauthGithubCallbackErrors[keyof AuthOauthGithubCallbackErrors];

export type AuthOauthGithubCallbackResponses = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthOauthGithubCallbackResponse =
  AuthOauthGithubCallbackResponses[keyof AuthOauthGithubCallbackResponses];

export type AuthOauthGithubStartData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Relative path to return to after a successful sign-in
     */
    redirect?: string;
  };
  url: "/auth/oauth/github/start";
};

export type AuthOauthGithubStartErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthOauthGithubStartError =
  AuthOauthGithubStartErrors[keyof AuthOauthGithubStartErrors];

export type AuthOauthGithubStartResponses = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthOauthGithubStartResponse =
  AuthOauthGithubStartResponses[keyof AuthOauthGithubStartResponses];

export type AuthOauthGoogleCallbackData = {
  body?: never;
  path?: never;
  query?: {
    code?: string;
    state?: string;
    error?: string;
  };
  url: "/auth/oauth/google/callback";
};

export type AuthOauthGoogleCallbackErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthOauthGoogleCallbackError =
  AuthOauthGoogleCallbackErrors[keyof AuthOauthGoogleCallbackErrors];

export type AuthOauthGoogleCallbackResponses = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthOauthGoogleCallbackResponse =
  AuthOauthGoogleCallbackResponses[keyof AuthOauthGoogleCallbackResponses];

export type AuthOauthGoogleStartData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Relative path to return to after a successful sign-in
     */
    redirect?: string;
  };
  url: "/auth/oauth/google/start";
};

export type AuthOauthGoogleStartErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthOauthGoogleStartError =
  AuthOauthGoogleStartErrors[keyof AuthOauthGoogleStartErrors];

export type AuthOauthGoogleStartResponses = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthOauthGoogleStartResponse =
  AuthOauthGoogleStartResponses[keyof AuthOauthGoogleStartResponses];

export type AuthRegisterData = {
  body: RegisterInputBodyWritable;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type AuthRegisterErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthRegisterError = AuthRegisterErrors[keyof AuthRegisterErrors];

export type AuthRegisterResponses = {
  /**
   * OK
   */
  200: RedirectOutputBody;
};

export type AuthRegisterResponse =
  AuthRegisterResponses[keyof AuthRegisterResponses];

export type AuthResendVerificationData = {
  body: ResendVerificationInputBodyWritable;
  path?: never;
  query?: never;
  url: "/auth/resend-verification";
};

export type AuthResendVerificationErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthResendVerificationError =
  AuthResendVerificationErrors[keyof AuthResendVerificationErrors];

export type AuthResendVerificationResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthResendVerificationResponse =
  AuthResendVerificationResponses[keyof AuthResendVerificationResponses];

export type AuthResetPasswordData = {
  body: ResetPasswordInputBodyWritable;
  path?: never;
  query?: never;
  url: "/auth/reset-password";
};

export type AuthResetPasswordErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthResetPasswordError =
  AuthResetPasswordErrors[keyof AuthResetPasswordErrors];

export type AuthResetPasswordResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthResetPasswordResponse =
  AuthResetPasswordResponses[keyof AuthResetPasswordResponses];

export type AuthSessionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/session";
};

export type AuthSessionErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthSessionError = AuthSessionErrors[keyof AuthSessionErrors];

export type AuthSessionResponses = {
  /**
   * OK
   */
  200: SessionOutputBody;
};

export type AuthSessionResponse =
  AuthSessionResponses[keyof AuthSessionResponses];

export type AuthVerifyEmailData = {
  body: VerifyEmailInputBodyWritable;
  path?: never;
  query?: never;
  url: "/auth/verify-email";
};

export type AuthVerifyEmailErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type AuthVerifyEmailError =
  AuthVerifyEmailErrors[keyof AuthVerifyEmailErrors];

export type AuthVerifyEmailResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthVerifyEmailResponse =
  AuthVerifyEmailResponses[keyof AuthVerifyEmailResponses];

export type ListCollectionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/collections";
};

export type ListCollectionsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListCollectionsError =
  ListCollectionsErrors[keyof ListCollectionsErrors];

export type ListCollectionsResponses = {
  /**
   * OK
   */
  200: Array<CollectionWithTypes> | null;
};

export type ListCollectionsResponse =
  ListCollectionsResponses[keyof ListCollectionsResponses];

export type CreateCollectionData = {
  body: CreateCollectionInputBodyWritable;
  path?: never;
  query?: never;
  url: "/collections";
};

export type CreateCollectionErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateCollectionError =
  CreateCollectionErrors[keyof CreateCollectionErrors];

export type CreateCollectionResponses = {
  /**
   * Created
   */
  201: CollectionWithTypes;
};

export type CreateCollectionResponse =
  CreateCollectionResponses[keyof CreateCollectionResponses];

export type DeleteCollectionData = {
  body?: never;
  path: {
    /**
     * Collection id
     */
    id: string;
  };
  query?: never;
  url: "/collections/{id}";
};

export type DeleteCollectionErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type DeleteCollectionError =
  DeleteCollectionErrors[keyof DeleteCollectionErrors];

export type DeleteCollectionResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteCollectionResponse =
  DeleteCollectionResponses[keyof DeleteCollectionResponses];

export type GetCollectionData = {
  body?: never;
  path: {
    /**
     * Collection id
     */
    id: string;
  };
  query?: never;
  url: "/collections/{id}";
};

export type GetCollectionErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetCollectionError = GetCollectionErrors[keyof GetCollectionErrors];

export type GetCollectionResponses = {
  /**
   * OK
   */
  200: CollectionWithTypes;
};

export type GetCollectionResponse =
  GetCollectionResponses[keyof GetCollectionResponses];

export type UpdateCollectionData = {
  body: UpdateCollectionInputBodyWritable;
  path: {
    /**
     * Collection id
     */
    id: string;
  };
  query?: never;
  url: "/collections/{id}";
};

export type UpdateCollectionErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type UpdateCollectionError =
  UpdateCollectionErrors[keyof UpdateCollectionErrors];

export type UpdateCollectionResponses = {
  /**
   * OK
   */
  200: CollectionWithTypes;
};

export type UpdateCollectionResponse =
  UpdateCollectionResponses[keyof UpdateCollectionResponses];

export type SetCollectionFavoriteData = {
  body: FavoriteInputBodyWritable;
  path: {
    /**
     * Collection id
     */
    id: string;
  };
  query?: never;
  url: "/collections/{id}/favorite";
};

export type SetCollectionFavoriteErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type SetCollectionFavoriteError =
  SetCollectionFavoriteErrors[keyof SetCollectionFavoriteErrors];

export type SetCollectionFavoriteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type SetCollectionFavoriteResponse =
  SetCollectionFavoriteResponses[keyof SetCollectionFavoriteResponses];

export type CspReportData = {
  body: Blob | File;
  path?: never;
  query?: never;
  url: "/csp-report";
};

export type CspReportErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CspReportError = CspReportErrors[keyof CspReportErrors];

export type CspReportResponses = {
  /**
   * No Content
   */
  204: void;
};

export type CspReportResponse = CspReportResponses[keyof CspReportResponses];

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type GetHealthErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
  /**
   * OK
   */
  200: HealthOutputBody;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ListItemsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Query variant: recent|type|collection|favorites
     */
    type: string;
    /**
     * Item type name (required when type=type)
     */
    typeName?: string;
    /**
     * Collection id (required when type=collection)
     */
    collectionId?: string;
    /**
     * Keyset cursor: last id of the previous page
     */
    cursor?: string;
    /**
     * Max items to return; out of range falls back to page size
     */
    limit?: number;
  };
  url: "/items";
};

export type ListItemsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListItemsError = ListItemsErrors[keyof ListItemsErrors];

export type ListItemsResponses = {
  /**
   * OK
   */
  200: ItemsPage;
};

export type ListItemsResponse = ListItemsResponses[keyof ListItemsResponses];

export type CreateItemData = {
  body: CreateItemInputBodyWritable;
  path?: never;
  query?: never;
  url: "/items";
};

export type CreateItemErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
  /**
   * Created
   */
  201: LightItem;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
  body?: never;
  path: {
    /**
     * Item id
     */
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type DeleteItemErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type DeleteItemError = DeleteItemErrors[keyof DeleteItemErrors];

export type DeleteItemResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteItemResponse = DeleteItemResponses[keyof DeleteItemResponses];

export type GetItemData = {
  body?: never;
  path: {
    /**
     * Item id
     */
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type GetItemErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetItemError = GetItemErrors[keyof GetItemErrors];

export type GetItemResponses = {
  /**
   * OK
   */
  200: FullItem;
};

export type GetItemResponse = GetItemResponses[keyof GetItemResponses];

export type UpdateItemData = {
  body: UpdateItemInputBodyWritable;
  path: {
    /**
     * Item id
     */
    id: string;
  };
  query?: never;
  url: "/items/{id}";
};

export type UpdateItemErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type UpdateItemError = UpdateItemErrors[keyof UpdateItemErrors];

export type UpdateItemResponses = {
  /**
   * OK
   */
  200: ItemSavedDetails;
};

export type UpdateItemResponse = UpdateItemResponses[keyof UpdateItemResponses];

export type GetItemContentData = {
  body?: never;
  path: {
    /**
     * Item id
     */
    id: string;
  };
  query?: never;
  url: "/items/{id}/content";
};

export type GetItemContentErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetItemContentError =
  GetItemContentErrors[keyof GetItemContentErrors];

export type GetItemContentResponses = {
  /**
   * OK
   */
  200: ItemContent;
};

export type GetItemContentResponse =
  GetItemContentResponses[keyof GetItemContentResponses];

export type GetItemDetailsData = {
  body?: never;
  path: {
    /**
     * Item id
     */
    id: string;
  };
  query?: never;
  url: "/items/{id}/details";
};

export type GetItemDetailsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetItemDetailsError =
  GetItemDetailsErrors[keyof GetItemDetailsErrors];

export type GetItemDetailsResponses = {
  /**
   * OK
   */
  200: ItemDetails;
};

export type GetItemDetailsResponse =
  GetItemDetailsResponses[keyof GetItemDetailsResponses];

export type SetItemFavoriteData = {
  body: FavoriteInputBodyWritable;
  path: {
    /**
     * Item id
     */
    id: string;
  };
  query?: never;
  url: "/items/{id}/favorite";
};

export type SetItemFavoriteErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type SetItemFavoriteError =
  SetItemFavoriteErrors[keyof SetItemFavoriteErrors];

export type SetItemFavoriteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type SetItemFavoriteResponse =
  SetItemFavoriteResponses[keyof SetItemFavoriteResponses];

export type SetItemPinnedData = {
  body: PinnedInputBodyWritable;
  path: {
    /**
     * Item id
     */
    id: string;
  };
  query?: never;
  url: "/items/{id}/pinned";
};

export type SetItemPinnedErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type SetItemPinnedError = SetItemPinnedErrors[keyof SetItemPinnedErrors];

export type SetItemPinnedResponses = {
  /**
   * No Content
   */
  204: void;
};

export type SetItemPinnedResponse =
  SetItemPinnedResponses[keyof SetItemPinnedResponses];

export type DeleteAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/me";
};

export type DeleteAccountErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteAccountResponse =
  DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetPreferencesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/me/preferences";
};

export type GetPreferencesErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetPreferencesError =
  GetPreferencesErrors[keyof GetPreferencesErrors];

export type GetPreferencesResponses = {
  /**
   * OK
   */
  200: EditorPreferences;
};

export type GetPreferencesResponse =
  GetPreferencesResponses[keyof GetPreferencesResponses];

export type UpdatePreferencesData = {
  body: UpdatePreferencesInputBodyWritable;
  path?: never;
  query?: never;
  url: "/me/preferences";
};

export type UpdatePreferencesErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type UpdatePreferencesError =
  UpdatePreferencesErrors[keyof UpdatePreferencesErrors];

export type UpdatePreferencesResponses = {
  /**
   * OK
   */
  200: EditorPreferences;
};

export type UpdatePreferencesResponse =
  UpdatePreferencesResponses[keyof UpdatePreferencesResponses];

export type UpdateProfileData = {
  body: UpdateProfileInputBodyWritable;
  path?: never;
  query?: never;
  url: "/me/profile";
};

export type UpdateProfileErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
  /**
   * OK
   */
  200: ProfileOutputBody;
};

export type UpdateProfileResponse =
  UpdateProfileResponses[keyof UpdateProfileResponses];

export type GetReadinessData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/readyz";
};

export type GetReadinessErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetReadinessError = GetReadinessErrors[keyof GetReadinessErrors];

export type GetReadinessResponses = {
  /**
   * OK
   */
  200: HealthOutputBody;
};

export type GetReadinessResponse =
  GetReadinessResponses[keyof GetReadinessResponses];

export type GlobalSearchData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Search query
     */
    q: string;
  };
  url: "/search";
};

export type GlobalSearchErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GlobalSearchError = GlobalSearchErrors[keyof GlobalSearchErrors];

export type GlobalSearchResponses = {
  /**
   * OK
   */
  200: SearchResult;
};

export type GlobalSearchResponse =
  GlobalSearchResponses[keyof GlobalSearchResponses];

export type GetStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/stats";
};

export type GetStatsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetStatsError = GetStatsErrors[keyof GetStatsErrors];

export type GetStatsResponses = {
  /**
   * OK
   */
  200: StatsOutputBody;
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];

export type GetActivityData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/stats/activity";
};

export type GetActivityErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetActivityError = GetActivityErrors[keyof GetActivityErrors];

export type GetActivityResponses = {
  /**
   * OK
   */
  200: ActivityOutputBody;
};

export type GetActivityResponse =
  GetActivityResponses[keyof GetActivityResponses];
