// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcdb

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, "emailVerified", name, image, password, "isPro", "stripeCustomerId", "stripeSubscriptionId", "createdAt", "updatedAt", "editorPreferences", "stripeSubscriptionStart", "stripeCurrentPeriodEnd", "proExpiredAt", "stripeCancelAtPeriodEnd", "stripeSubscriptionInterval", "stripeLastSyncAt", "stripeSubscriptionStatus", "credentialEmail", "credentialEmailVerified" FROM users WHERE email = $1
`

// Credentials login / account lookup by email.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.Image,
		&i.Password,
		&i.IsPro,
		&i.StripeCustomerId,
		&i.StripeSubscriptionId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditorPreferences,
		&i.StripeSubscriptionStart,
		&i.StripeCurrentPeriodEnd,
		&i.ProExpiredAt,
		&i.StripeCancelAtPeriodEnd,
		&i.StripeSubscriptionInterval,
		&i.StripeLastSyncAt,
		&i.StripeSubscriptionStatus,
		&i.CredentialEmail,
		&i.CredentialEmailVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, "emailVerified", name, image, password, "isPro", "stripeCustomerId", "stripeSubscriptionId", "createdAt", "updatedAt", "editorPreferences", "stripeSubscriptionStart", "stripeCurrentPeriodEnd", "proExpiredAt", "stripeCancelAtPeriodEnd", "stripeSubscriptionInterval", "stripeLastSyncAt", "stripeSubscriptionStatus", "credentialEmail", "credentialEmailVerified" FROM users WHERE id = $1
`

// Resolve the session's user. id comes from the session cookie, never user input.
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.Image,
		&i.Password,
		&i.IsPro,
		&i.StripeCustomerId,
		&i.StripeSubscriptionId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditorPreferences,
		&i.StripeSubscriptionStart,
		&i.StripeCurrentPeriodEnd,
		&i.ProExpiredAt,
		&i.StripeCancelAtPeriodEnd,
		&i.StripeSubscriptionInterval,
		&i.StripeLastSyncAt,
		&i.StripeSubscriptionStatus,
		&i.CredentialEmail,
		&i.CredentialEmailVerified,
	)
	return i, err
}
