// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlcdb

import (
	"context"
	"time"
)

const countCollectionsByUser = `-- name: CountCollectionsByUser :one
SELECT COUNT(*)::bigint FROM collections WHERE "userId" = $1
`

// Free-tier gate (canCreateCollection): the user's total collection count.
func (q *Queries) CountCollectionsByUser(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countCollectionsByUser, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (id, name, description, "userId", "updatedAt")
VALUES ($1, $2, $3, $4, now())
RETURNING id, name, description, "isFavorite", "createdAt", 0::int AS "itemCount"
`

type CreateCollectionParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Owner       string  `json:"owner"`
}

type CreateCollectionRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsFavorite  bool      `json:"isFavorite"`
	CreatedAt   time.Time `json:"createdAt"`
	ItemCount   int32     `json:"itemCount"`
}

// POST /collections. itemCount is always 0 for a fresh collection.
func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (CreateCollectionRow, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Owner,
	)
	var i CreateCollectionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.ItemCount,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :execrows
DELETE FROM collections WHERE id = $1 AND "userId" = $2
`

type DeleteCollectionParams struct {
	ID    string `json:"id"`
	Owner string `json:"owner"`
}

// DELETE /collections/{id}. Scoped delete; 0 rows → 404. item_collections rows cascade.
func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollection, arg.ID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT
    c.id,
    c.name,
    c.description,
    c."isFavorite",
    c."createdAt",
    (SELECT COUNT(*)::int FROM item_collections ic WHERE ic."collectionId" = c.id) AS "itemCount"
FROM collections c
WHERE c.id = $1 AND c."userId" = $2
`

type GetCollectionByIDParams struct {
	ID    string `json:"id"`
	Owner string `json:"owner"`
}

type GetCollectionByIDRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsFavorite  bool      `json:"isFavorite"`
	CreatedAt   time.Time `json:"createdAt"`
	ItemCount   int32     `json:"itemCount"`
}

// GET /collections/{id} and the re-read after create/update. Base shape; type chips joined
// on separately.
func (q *Queries) GetCollectionByID(ctx context.Context, arg GetCollectionByIDParams) (GetCollectionByIDRow, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, arg.ID, arg.Owner)
	var i GetCollectionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.ItemCount,
	)
	return i, err
}

const getCollectionTypeCounts = `-- name: GetCollectionTypeCounts :many
WITH type_counts AS (
    SELECT
        ic."collectionId",
        it.id,
        it.name,
        it.icon,
        it.color,
        it."isSystem",
        COUNT(*)::int AS count
    FROM item_collections ic
    JOIN collections co ON co.id = ic."collectionId" AND co."userId" = $1
    JOIN items i ON ic."itemId" = i.id
    JOIN item_types it ON i."itemTypeId" = it.id
    WHERE ic."collectionId" = ANY($2::text[])
    GROUP BY ic."collectionId", it.id, it.name, it.icon, it.color, it."isSystem"
),
ranked AS (
    SELECT
        "collectionId", id, name, icon, color, "isSystem", count,
        ROW_NUMBER() OVER (PARTITION BY "collectionId" ORDER BY count DESC) AS rn
    FROM type_counts
)
SELECT "collectionId", id, name, icon, color, "isSystem", count
FROM ranked
WHERE rn <= 4
ORDER BY "collectionId", count DESC
`

type GetCollectionTypeCountsParams struct {
	Owner         string   `json:"owner"`
	CollectionIds []string `json:"collection_ids"`
}

type GetCollectionTypeCountsRow struct {
	CollectionId string `json:"collectionId"`
	ID           string `json:"id"`
	Name         string `json:"name"`
	Icon         string `json:"icon"`
	Color        string `json:"color"`
	IsSystem     bool   `json:"isSystem"`
	Count        int32  `json:"count"`
}

// The top-4 item types per collection, ranked by count (ROW_NUMBER() OVER PARTITION BY
// collectionId). Ported 1:1 from getCollectionTypeCounts. Takes the set of collection ids
// the handler is rendering, and scopes them by the session owner so the query is IDOR-safe
// on its own (not merely because its callers pass owner-scoped ids).
func (q *Queries) GetCollectionTypeCounts(ctx context.Context, arg GetCollectionTypeCountsParams) ([]GetCollectionTypeCountsRow, error) {
	rows, err := q.db.Query(ctx, getCollectionTypeCounts, arg.Owner, arg.CollectionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollectionTypeCountsRow
	for rows.Next() {
		var i GetCollectionTypeCountsRow
		if err := rows.Scan(
			&i.CollectionId,
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.IsSystem,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many

SELECT
    c.id,
    c.name,
    c.description,
    c."isFavorite",
    c."createdAt",
    (SELECT COUNT(*)::int FROM item_collections ic WHERE ic."collectionId" = c.id) AS "itemCount"
FROM collections c
WHERE c."userId" = $1
ORDER BY c."isFavorite" DESC, c."updatedAt" DESC
`

type ListCollectionsRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsFavorite  bool      `json:"isFavorite"`
	CreatedAt   time.Time `json:"createdAt"`
	ItemCount   int32     `json:"itemCount"`
}

// Collections domain queries (Phase 2). Every read and write is scoped by the session
// userId (IDOR-safe). itemCount is the count of item_collections rows for the collection.
// The per-collection top-4 item-type breakdown is fetched separately via
// GetCollectionTypeCounts (the ROW_NUMBER() window ported 1:1 from getCollectionTypeCounts).
// GET /collections (getAllCollections): favorites first, then most-recently-updated. Type
// chips are joined on in the handler via GetCollectionTypeCounts.
func (q *Queries) ListCollections(ctx context.Context, owner string) ([]ListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCollections, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionsRow
	for rows.Next() {
		var i ListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCollectionFavorite = `-- name: SetCollectionFavorite :execrows
UPDATE collections SET "isFavorite" = $1, "updatedAt" = now()
WHERE id = $2 AND "userId" = $3
`

type SetCollectionFavoriteParams struct {
	IsFavorite bool   `json:"is_favorite"`
	ID         string `json:"id"`
	Owner      string `json:"owner"`
}

// PATCH /collections/{id}/favorite. Scoped update; 0 rows → 404.
func (q *Queries) SetCollectionFavorite(ctx context.Context, arg SetCollectionFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCollectionFavorite, arg.IsFavorite, arg.ID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCollection = `-- name: UpdateCollection :execrows
UPDATE collections SET
    name = COALESCE($1, name),
    description = CASE WHEN $2::bool THEN $3 ELSE description END,
    "isFavorite" = COALESCE($4, "isFavorite"),
    "updatedAt" = now()
WHERE id = $5 AND "userId" = $6
`

type UpdateCollectionParams struct {
	Name           *string `json:"name"`
	DescriptionSet bool    `json:"description_set"`
	Description    *string `json:"description"`
	IsFavorite     *bool   `json:"is_favorite"`
	ID             string  `json:"id"`
	Owner          string  `json:"owner"`
}

// PATCH /collections/{id}. A partial update: name and isFavorite fall back to the current
// value when omitted (COALESCE); description is set only when the caller marks it provided
// (description_set), so it can be explicitly cleared to NULL without a null param being
// mistaken for "unchanged". Scoped; 0 rows → 404.
func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCollection,
		arg.Name,
		arg.DescriptionSet,
		arg.Description,
		arg.IsFavorite,
		arg.ID,
		arg.Owner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
