// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcdb

import (
	"context"
	"time"
)

const countItemsByUser = `-- name: CountItemsByUser :one
SELECT COUNT(*)::bigint FROM items WHERE "userId" = $1
`

// Free-tier gate (canCreateItem): the user's total item count.
func (q *Queries) CountItemsByUser(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsByUser, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createItem = `-- name: CreateItem :one
WITH resolved_type AS (
    SELECT it0.id FROM item_types it0
    WHERE it0.name = $1
        AND (it0."userId" IS NULL OR it0."userId" = $2)
    ORDER BY (it0."userId" IS NULL) DESC
    LIMIT 1
),
new_item AS (
    INSERT INTO items (
        id, "userId", "itemTypeId", title, "contentType",
        description, content, url, "fileUrl", "fileName", "fileSize",
        "imageWidth", "imageHeight", language, "updatedAt"
    )
    SELECT
        $3, $2, rt.id, $4, $5,
        $6, $7, $8,
        $9, $10, $11,
        $12, $13, $14, now()
    FROM resolved_type rt
    RETURNING id, title, "contentType", content, "fileUrl", "fileName", "fileSize", url, description, "isFavorite", "isPinned", language, "createdAt", "updatedAt", "userId", "itemTypeId", "imageHeight", "imageWidth"
),
ins_tags AS (
    INSERT INTO tags (id, name)
    SELECT unnest($15::text[]), unnest($16::text[])
    WHERE EXISTS (SELECT 1 FROM new_item)
    ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
    RETURNING id, name
),
link_tags AS (
    INSERT INTO "_ItemTags" ("A", "B")
    SELECT ni.id, itg.id FROM new_item ni CROSS JOIN ins_tags itg
    ON CONFLICT ("A", "B") DO NOTHING
),
link_cols AS (
    INSERT INTO item_collections ("itemId", "collectionId", "addedAt")
    SELECT ni.id, c.id, now()
    FROM new_item ni
    JOIN collections c ON c.id = ANY($17::text[]) AND c."userId" = $2
    ON CONFLICT ("itemId", "collectionId") DO NOTHING
)
SELECT
    ni.id,
    ni.title,
    ni."createdAt",
    ni.url,
    ni."fileName",
    ni."fileSize",
    ni."isFavorite",
    ni."isPinned",
    $1::text AS "itemTypeName",
    COALESCE(LEFT(ni.description, 150), '')::text AS "descriptionPreview",
    COALESCE(LEFT(ni.content, 150), '')::text AS "contentPreview",
    COALESCE((SELECT array_agg(name ORDER BY name) FROM ins_tags), '{}'::text[])::text[] AS tags
FROM new_item ni
`

type CreateItemParams struct {
	ItemTypeName  string      `json:"item_type_name"`
	Owner         *string     `json:"owner"`
	ID            string      `json:"id"`
	Title         string      `json:"title"`
	ContentType   ContentType `json:"content_type"`
	Description   *string     `json:"description"`
	Content       *string     `json:"content"`
	Url           *string     `json:"url"`
	FileUrl       *string     `json:"file_url"`
	FileName      *string     `json:"file_name"`
	FileSize      *int32      `json:"file_size"`
	ImageWidth    *int32      `json:"image_width"`
	ImageHeight   *int32      `json:"image_height"`
	Language      *string     `json:"language"`
	TagIds        []string    `json:"tag_ids"`
	TagNames      []string    `json:"tag_names"`
	CollectionIds []string    `json:"collection_ids"`
}

type CreateItemRow struct {
	ID                 string    `json:"id"`
	Title              string    `json:"title"`
	CreatedAt          time.Time `json:"createdAt"`
	Url                *string   `json:"url"`
	FileName           *string   `json:"fileName"`
	FileSize           *int32    `json:"fileSize"`
	IsFavorite         bool      `json:"isFavorite"`
	IsPinned           bool      `json:"isPinned"`
	ItemTypeName       string    `json:"itemTypeName"`
	DescriptionPreview string    `json:"descriptionPreview"`
	ContentPreview     string    `json:"contentPreview"`
	Tags               []string  `json:"tags"`
}

// POST /items. One statement: resolve the type, insert the item, connect-or-create its
// tags (ON CONFLICT(name) keeps the existing row and its id — the injected id is used only
// for genuinely new tags), link the tags and the owned collections, then return the
// LightItem shape. An unknown type resolves to zero rows → the item is never inserted → the
// final SELECT returns no rows (ErrNoRows), which the handler maps to a 500 (parity: a
// createItem returning null → "Failed to create item.").
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ItemTypeName,
		arg.Owner,
		arg.ID,
		arg.Title,
		arg.ContentType,
		arg.Description,
		arg.Content,
		arg.Url,
		arg.FileUrl,
		arg.FileName,
		arg.FileSize,
		arg.ImageWidth,
		arg.ImageHeight,
		arg.Language,
		arg.TagIds,
		arg.TagNames,
		arg.CollectionIds,
	)
	var i CreateItemRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.Url,
		&i.FileName,
		&i.FileSize,
		&i.IsFavorite,
		&i.IsPinned,
		&i.ItemTypeName,
		&i.DescriptionPreview,
		&i.ContentPreview,
		&i.Tags,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM items WHERE id = $1 AND "userId" = $2
`

type DeleteItemParams struct {
	ID    string `json:"id"`
	Owner string `json:"owner"`
}

// DELETE /items/{id}. Scoped delete; returns the affected-row count (0 → 404).
func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, arg.ID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT
    i.id,
    i.title,
    i."createdAt",
    i."updatedAt",
    i.url,
    i."fileName",
    i."fileSize",
    i."isFavorite",
    i."isPinned",
    i.description,
    i.content,
    i.language,
    it.name AS "itemTypeName",
    COALESCE(array_agg(DISTINCT t.name) FILTER (WHERE t.name IS NOT NULL), '{}'::text[])::text[] AS tags,
    COALESCE(
        jsonb_agg(DISTINCT jsonb_build_object('id', col.id, 'name', col.name))
            FILTER (WHERE col.id IS NOT NULL),
        '[]'::jsonb
    )::jsonb AS collections
FROM items i
JOIN item_types it ON it.id = i."itemTypeId"
LEFT JOIN "_ItemTags" itag ON itag."A" = i.id
LEFT JOIN tags t ON t.id = itag."B"
LEFT JOIN item_collections ic ON ic."itemId" = i.id
LEFT JOIN collections col ON col.id = ic."collectionId"
WHERE i.id = $1 AND i."userId" = $2
GROUP BY i.id, it.name
`

type GetItemByIDParams struct {
	ID    string `json:"id"`
	Owner string `json:"owner"`
}

type GetItemByIDRow struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	Url          *string   `json:"url"`
	FileName     *string   `json:"fileName"`
	FileSize     *int32    `json:"fileSize"`
	IsFavorite   bool      `json:"isFavorite"`
	IsPinned     bool      `json:"isPinned"`
	Description  *string   `json:"description"`
	Content      *string   `json:"content"`
	Language     *string   `json:"language"`
	ItemTypeName string    `json:"itemTypeName"`
	Tags         []string  `json:"tags"`
	Collections  []byte    `json:"collections"`
}

// GET /items/{id}: the full drawer shape (FullItem). Returns raw description/content so
// the handler computes the 150-char previews (parity with toFullItem's slice(0,150)).
func (q *Queries) GetItemByID(ctx context.Context, arg GetItemByIDParams) (GetItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getItemByID, arg.ID, arg.Owner)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.FileName,
		&i.FileSize,
		&i.IsFavorite,
		&i.IsPinned,
		&i.Description,
		&i.Content,
		&i.Language,
		&i.ItemTypeName,
		&i.Tags,
		&i.Collections,
	)
	return i, err
}

const getItemContent = `-- name: GetItemContent :one
SELECT content, language FROM items
WHERE id = $1 AND "userId" = $2
`

type GetItemContentParams struct {
	ID    string `json:"id"`
	Owner string `json:"owner"`
}

type GetItemContentRow struct {
	Content  *string `json:"content"`
	Language *string `json:"language"`
}

// GET /items/{id}/content: content + language for content-bearing types.
func (q *Queries) GetItemContent(ctx context.Context, arg GetItemContentParams) (GetItemContentRow, error) {
	row := q.db.QueryRow(ctx, getItemContent, arg.ID, arg.Owner)
	var i GetItemContentRow
	err := row.Scan(&i.Content, &i.Language)
	return i, err
}

const getItemDetails = `-- name: GetItemDetails :one
SELECT
    i.description,
    i."updatedAt",
    COALESCE(
        jsonb_agg(DISTINCT jsonb_build_object('id', col.id, 'name', col.name))
            FILTER (WHERE col.id IS NOT NULL),
        '[]'::jsonb
    )::jsonb AS collections
FROM items i
LEFT JOIN item_collections ic ON ic."itemId" = i.id
LEFT JOIN collections col ON col.id = ic."collectionId"
WHERE i.id = $1 AND i."userId" = $2
GROUP BY i.id
`

type GetItemDetailsParams struct {
	ID    string `json:"id"`
	Owner string `json:"owner"`
}

type GetItemDetailsRow struct {
	Description *string   `json:"description"`
	UpdatedAt   time.Time `json:"updatedAt"`
	Collections []byte    `json:"collections"`
}

// GET /items/{id}/details: only the fields LightItem doesn't carry.
func (q *Queries) GetItemDetails(ctx context.Context, arg GetItemDetailsParams) (GetItemDetailsRow, error) {
	row := q.db.QueryRow(ctx, getItemDetails, arg.ID, arg.Owner)
	var i GetItemDetailsRow
	err := row.Scan(&i.Description, &i.UpdatedAt, &i.Collections)
	return i, err
}

const getItemForAuth = `-- name: GetItemForAuth :one
SELECT i.id, i."itemTypeId", i."fileUrl", i."fileName", it.name AS "itemTypeName"
FROM items i
JOIN item_types it ON it.id = i."itemTypeId"
WHERE i.id = $1 AND i."userId" = $2
`

type GetItemForAuthParams struct {
	ID    string `json:"id"`
	Owner string `json:"owner"`
}

type GetItemForAuthRow struct {
	ID           string  `json:"id"`
	ItemTypeId   string  `json:"itemTypeId"`
	FileUrl      *string `json:"fileUrl"`
	FileName     *string `json:"fileName"`
	ItemTypeName string  `json:"itemTypeName"`
}

// Server-only mutation guard (PATCH/DELETE): the item's id, current type id + name, and
// file reference so the handler can enforce the Pro gate and the source-type retype guard,
// and reuse the current type id when a PATCH does not retype (no extra lookup).
func (q *Queries) GetItemForAuth(ctx context.Context, arg GetItemForAuthParams) (GetItemForAuthRow, error) {
	row := q.db.QueryRow(ctx, getItemForAuth, arg.ID, arg.Owner)
	var i GetItemForAuthRow
	err := row.Scan(
		&i.ID,
		&i.ItemTypeId,
		&i.FileUrl,
		&i.FileName,
		&i.ItemTypeName,
	)
	return i, err
}

const getItemTypeByName = `-- name: GetItemTypeByName :one
SELECT id FROM item_types
WHERE name = $1 AND ("userId" IS NULL OR "userId" = $2)
ORDER BY ("userId" IS NULL) DESC
LIMIT 1
`

type GetItemTypeByNameParams struct {
	Name  string  `json:"name"`
	Owner *string `json:"owner"`
}

// Resolve an item type name to its id, preferring the system type (userId NULL) over a
// user's same-named custom type (parity: systemTypes.find(...) ?? custom lookup).
func (q *Queries) GetItemTypeByName(ctx context.Context, arg GetItemTypeByNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getItemTypeByName, arg.Name, arg.Owner)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listFavoriteItems = `-- name: ListFavoriteItems :many
SELECT
    i.id,
    i.title,
    i."createdAt",
    i.url,
    i."fileName",
    i."fileSize",
    i."isFavorite",
    i."isPinned",
    it.name AS "itemTypeName",
    COALESCE(LEFT(i.description, 150), '')::text AS "descriptionPreview",
    COALESCE(LEFT(i.content, 150), '')::text AS "contentPreview",
    COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}'::text[])::text[] AS tags
FROM items i
JOIN item_types it ON it.id = i."itemTypeId"
LEFT JOIN "_ItemTags" itag ON itag."A" = i.id
LEFT JOIN tags t ON t.id = itag."B"
WHERE i."userId" = $1
    AND i."isFavorite" = true
    AND (
        $2::text IS NULL
        OR EXISTS (
            SELECT 1 FROM items c
            WHERE c.id = $2 AND c."userId" = $1
                AND (i."updatedAt", i.id) < (c."updatedAt", c.id)
        )
    )
GROUP BY i.id, it.name
ORDER BY i."updatedAt" DESC, i.id DESC
LIMIT $3
`

type ListFavoriteItemsParams struct {
	Owner     string  `json:"owner"`
	Cursor    *string `json:"cursor"`
	PageLimit int32   `json:"page_limit"`
}

type ListFavoriteItemsRow struct {
	ID                 string    `json:"id"`
	Title              string    `json:"title"`
	CreatedAt          time.Time `json:"createdAt"`
	Url                *string   `json:"url"`
	FileName           *string   `json:"fileName"`
	FileSize           *int32    `json:"fileSize"`
	IsFavorite         bool      `json:"isFavorite"`
	IsPinned           bool      `json:"isPinned"`
	ItemTypeName       string    `json:"itemTypeName"`
	DescriptionPreview string    `json:"descriptionPreview"`
	ContentPreview     string    `json:"contentPreview"`
	Tags               []string  `json:"tags"`
}

// GET /items?type=favorites — favorites use a distinct order (updatedAt desc, id desc),
// so the keyset compares the (updatedAt, id) tuple instead of (isPinned, createdAt, id).
func (q *Queries) ListFavoriteItems(ctx context.Context, arg ListFavoriteItemsParams) ([]ListFavoriteItemsRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteItems, arg.Owner, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoriteItemsRow
	for rows.Next() {
		var i ListFavoriteItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.Url,
			&i.FileName,
			&i.FileSize,
			&i.IsFavorite,
			&i.IsPinned,
			&i.ItemTypeName,
			&i.DescriptionPreview,
			&i.ContentPreview,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCollection = `-- name: ListItemsByCollection :many
SELECT
    i.id,
    i.title,
    i."createdAt",
    i.url,
    i."fileName",
    i."fileSize",
    i."isFavorite",
    i."isPinned",
    it.name AS "itemTypeName",
    COALESCE(LEFT(i.description, 150), '')::text AS "descriptionPreview",
    COALESCE(LEFT(i.content, 150), '')::text AS "contentPreview",
    COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}'::text[])::text[] AS tags
FROM items i
JOIN item_types it ON it.id = i."itemTypeId"
LEFT JOIN "_ItemTags" itag ON itag."A" = i.id
LEFT JOIN tags t ON t.id = itag."B"
WHERE i."userId" = $1
    AND EXISTS (
        SELECT 1 FROM item_collections ic
        WHERE ic."itemId" = i.id AND ic."collectionId" = $2
    )
    AND (
        $3::text IS NULL
        OR EXISTS (
            SELECT 1 FROM items c
            WHERE c.id = $3 AND c."userId" = $1
                AND (i."isPinned", i."createdAt", i.id) < (c."isPinned", c."createdAt", c.id)
        )
    )
GROUP BY i.id, it.name
ORDER BY i."isPinned" DESC, i."createdAt" DESC, i.id DESC
LIMIT $4
`

type ListItemsByCollectionParams struct {
	Owner        string  `json:"owner"`
	CollectionID string  `json:"collection_id"`
	Cursor       *string `json:"cursor"`
	PageLimit    int32   `json:"page_limit"`
}

type ListItemsByCollectionRow struct {
	ID                 string    `json:"id"`
	Title              string    `json:"title"`
	CreatedAt          time.Time `json:"createdAt"`
	Url                *string   `json:"url"`
	FileName           *string   `json:"fileName"`
	FileSize           *int32    `json:"fileSize"`
	IsFavorite         bool      `json:"isFavorite"`
	IsPinned           bool      `json:"isPinned"`
	ItemTypeName       string    `json:"itemTypeName"`
	DescriptionPreview string    `json:"descriptionPreview"`
	ContentPreview     string    `json:"contentPreview"`
	Tags               []string  `json:"tags"`
}

// GET /items?type=collection&collectionId=... — same keyset order, membership-filtered.
func (q *Queries) ListItemsByCollection(ctx context.Context, arg ListItemsByCollectionParams) ([]ListItemsByCollectionRow, error) {
	rows, err := q.db.Query(ctx, listItemsByCollection,
		arg.Owner,
		arg.CollectionID,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByCollectionRow
	for rows.Next() {
		var i ListItemsByCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.Url,
			&i.FileName,
			&i.FileSize,
			&i.IsFavorite,
			&i.IsPinned,
			&i.ItemTypeName,
			&i.DescriptionPreview,
			&i.ContentPreview,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByType = `-- name: ListItemsByType :many
SELECT
    i.id,
    i.title,
    i."createdAt",
    i.url,
    i."fileName",
    i."fileSize",
    i."isFavorite",
    i."isPinned",
    it.name AS "itemTypeName",
    COALESCE(LEFT(i.description, 150), '')::text AS "descriptionPreview",
    COALESCE(LEFT(i.content, 150), '')::text AS "contentPreview",
    COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}'::text[])::text[] AS tags
FROM items i
JOIN item_types it ON it.id = i."itemTypeId"
LEFT JOIN "_ItemTags" itag ON itag."A" = i.id
LEFT JOIN tags t ON t.id = itag."B"
WHERE i."userId" = $1
    AND it.name = $2
    AND (
        $3::text IS NULL
        OR EXISTS (
            SELECT 1 FROM items c
            WHERE c.id = $3 AND c."userId" = $1
                AND (i."isPinned", i."createdAt", i.id) < (c."isPinned", c."createdAt", c.id)
        )
    )
GROUP BY i.id, it.name
ORDER BY i."isPinned" DESC, i."createdAt" DESC, i.id DESC
LIMIT $4
`

type ListItemsByTypeParams struct {
	Owner     string  `json:"owner"`
	TypeName  string  `json:"type_name"`
	Cursor    *string `json:"cursor"`
	PageLimit int32   `json:"page_limit"`
}

type ListItemsByTypeRow struct {
	ID                 string    `json:"id"`
	Title              string    `json:"title"`
	CreatedAt          time.Time `json:"createdAt"`
	Url                *string   `json:"url"`
	FileName           *string   `json:"fileName"`
	FileSize           *int32    `json:"fileSize"`
	IsFavorite         bool      `json:"isFavorite"`
	IsPinned           bool      `json:"isPinned"`
	ItemTypeName       string    `json:"itemTypeName"`
	DescriptionPreview string    `json:"descriptionPreview"`
	ContentPreview     string    `json:"contentPreview"`
	Tags               []string  `json:"tags"`
}

// GET /items?type=type&typeName=... — same keyset order, filtered to one item type name.
func (q *Queries) ListItemsByType(ctx context.Context, arg ListItemsByTypeParams) ([]ListItemsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listItemsByType,
		arg.Owner,
		arg.TypeName,
		arg.Cursor,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByTypeRow
	for rows.Next() {
		var i ListItemsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.Url,
			&i.FileName,
			&i.FileSize,
			&i.IsFavorite,
			&i.IsPinned,
			&i.ItemTypeName,
			&i.DescriptionPreview,
			&i.ContentPreview,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentItems = `-- name: ListRecentItems :many

SELECT
    i.id,
    i.title,
    i."createdAt",
    i.url,
    i."fileName",
    i."fileSize",
    i."isFavorite",
    i."isPinned",
    it.name AS "itemTypeName",
    COALESCE(LEFT(i.description, 150), '')::text AS "descriptionPreview",
    COALESCE(LEFT(i.content, 150), '')::text AS "contentPreview",
    COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}'::text[])::text[] AS tags
FROM items i
JOIN item_types it ON it.id = i."itemTypeId"
LEFT JOIN "_ItemTags" itag ON itag."A" = i.id
LEFT JOIN tags t ON t.id = itag."B"
WHERE i."userId" = $1
    AND (
        $2::text IS NULL
        OR EXISTS (
            SELECT 1 FROM items c
            WHERE c.id = $2 AND c."userId" = $1
                AND (i."isPinned", i."createdAt", i.id) < (c."isPinned", c."createdAt", c.id)
        )
    )
GROUP BY i.id, it.name
ORDER BY i."isPinned" DESC, i."createdAt" DESC, i.id DESC
LIMIT $3
`

type ListRecentItemsParams struct {
	Owner     string  `json:"owner"`
	Cursor    *string `json:"cursor"`
	PageLimit int32   `json:"page_limit"`
}

type ListRecentItemsRow struct {
	ID                 string    `json:"id"`
	Title              string    `json:"title"`
	CreatedAt          time.Time `json:"createdAt"`
	Url                *string   `json:"url"`
	FileName           *string   `json:"fileName"`
	FileSize           *int32    `json:"fileSize"`
	IsFavorite         bool      `json:"isFavorite"`
	IsPinned           bool      `json:"isPinned"`
	ItemTypeName       string    `json:"itemTypeName"`
	DescriptionPreview string    `json:"descriptionPreview"`
	ContentPreview     string    `json:"contentPreview"`
	Tags               []string  `json:"tags"`
}

// Items domain queries (Phase 2). Every read and write is scoped by the session
// userId ($owner / sqlc.arg('owner')), never a path/body value (IDOR-safe). Tags are
// written through the implicit Prisma join table "_ItemTags" (A = item id, B = tag id);
// new tag ids come from the injected IDs func (UUIDv7), matching Phase 1.
//
// The LightItem projection (id, title, createdAt, url, file fields, favorite/pinned,
// itemType name, LEFT(...,150) previews, and the aggregated tag names) is repeated across
// the four list queries and the search query. Unlike the Next app's per-type selects
// (LIGHT_ITEM_SELECT{,_FILE,_IMAGE}), the Go queries return one uniform superset shape for
// every type — a file/image row now carries its tags/url instead of the lossy []/null the
// TS optimization dropped. The wire shape is a superset, never missing a field.
// GET /items?type=recent. Keyset pagination on (isPinned desc, createdAt desc, id desc);
// LIMIT is PAGE_SIZE+1 so the handler detects hasMore. A null cursor is the first page.
func (q *Queries) ListRecentItems(ctx context.Context, arg ListRecentItemsParams) ([]ListRecentItemsRow, error) {
	rows, err := q.db.Query(ctx, listRecentItems, arg.Owner, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentItemsRow
	for rows.Next() {
		var i ListRecentItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.Url,
			&i.FileName,
			&i.FileSize,
			&i.IsFavorite,
			&i.IsPinned,
			&i.ItemTypeName,
			&i.DescriptionPreview,
			&i.ContentPreview,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItemFavorite = `-- name: SetItemFavorite :execrows
UPDATE items SET "isFavorite" = $1, "updatedAt" = now()
WHERE id = $2 AND "userId" = $3
`

type SetItemFavoriteParams struct {
	IsFavorite bool   `json:"is_favorite"`
	ID         string `json:"id"`
	Owner      string `json:"owner"`
}

// PATCH /items/{id}/favorite. Scoped update; 0 rows → 404. updatedAt is bumped to match
// Prisma's @updatedAt (the favorites list orders by updatedAt, so the toggle must move it).
func (q *Queries) SetItemFavorite(ctx context.Context, arg SetItemFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemFavorite, arg.IsFavorite, arg.ID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setItemPinned = `-- name: SetItemPinned :execrows
UPDATE items SET "isPinned" = $1, "updatedAt" = now()
WHERE id = $2 AND "userId" = $3
`

type SetItemPinnedParams struct {
	IsPinned bool   `json:"is_pinned"`
	ID       string `json:"id"`
	Owner    string `json:"owner"`
}

// PATCH /items/{id}/pinned. Scoped update; 0 rows → 404. updatedAt is bumped to match
// Prisma's @updatedAt.
func (q *Queries) SetItemPinned(ctx context.Context, arg SetItemPinnedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemPinned, arg.IsPinned, arg.ID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateItem = `-- name: UpdateItem :one
WITH upd AS (
    UPDATE items AS itm SET
        title = $3,
        description = $4,
        content = $5,
        url = $6,
        language = $7,
        "itemTypeId" = $8,
        "updatedAt" = now()
    WHERE itm.id = $9 AND itm."userId" = $2
    RETURNING itm.id, itm.title, itm."contentType", itm.content, itm."fileUrl", itm."fileName", itm."fileSize", itm.url, itm.description, itm."isFavorite", itm."isPinned", itm.language, itm."createdAt", itm."updatedAt", itm."userId", itm."itemTypeId", itm."imageHeight", itm."imageWidth"
),
ins_tags AS (
    INSERT INTO tags (id, name)
    SELECT unnest($10::text[]), unnest($11::text[])
    WHERE EXISTS (SELECT 1 FROM upd)
    ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
    RETURNING id, name
),
del_tags AS (
    DELETE FROM "_ItemTags"
    WHERE "A" IN (SELECT id FROM upd)
        AND "B" <> ALL(ARRAY(SELECT id FROM ins_tags))
),
del_cols AS (
    DELETE FROM item_collections
    WHERE "itemId" IN (SELECT id FROM upd)
        AND "collectionId" <> ALL($1::text[])
),
link_tags AS (
    INSERT INTO "_ItemTags" ("A", "B")
    SELECT u.id, itg.id FROM upd u CROSS JOIN ins_tags itg
    ON CONFLICT ("A", "B") DO NOTHING
),
link_cols AS (
    INSERT INTO item_collections ("itemId", "collectionId", "addedAt")
    SELECT u.id, c.id, now()
    FROM upd u
    JOIN collections c ON c.id = ANY($1::text[]) AND c."userId" = $2
    ON CONFLICT ("itemId", "collectionId") DO NOTHING
)
SELECT
    u.description,
    u."updatedAt",
    u.url,
    u."isFavorite",
    u."isPinned",
    COALESCE((SELECT array_agg(name ORDER BY name) FROM ins_tags), '{}'::text[])::text[] AS tags,
    COALESCE(
        (
            SELECT jsonb_agg(jsonb_build_object('id', c.id, 'name', c.name) ORDER BY c.name)
            FROM collections c
            WHERE c.id = ANY($1::text[]) AND c."userId" = $2
        ),
        '[]'::jsonb
    )::jsonb AS collections
FROM upd u
`

type UpdateItemParams struct {
	CollectionIds []string `json:"collection_ids"`
	Owner         string   `json:"owner"`
	Title         string   `json:"title"`
	Description   *string  `json:"description"`
	Content       *string  `json:"content"`
	Url           *string  `json:"url"`
	Language      *string  `json:"language"`
	ItemTypeID    string   `json:"item_type_id"`
	ID            string   `json:"id"`
	TagIds        []string `json:"tag_ids"`
	TagNames      []string `json:"tag_names"`
}

type UpdateItemRow struct {
	Description *string   `json:"description"`
	UpdatedAt   time.Time `json:"updatedAt"`
	Url         *string   `json:"url"`
	IsFavorite  bool      `json:"isFavorite"`
	IsPinned    bool      `json:"isPinned"`
	Tags        []string  `json:"tags"`
	Collections []byte    `json:"collections"`
}

// PATCH /items/{id}. The handler resolves the final item-type id first (the retyped target,
// or the item's current type id when the PATCH does not retype), so item_type_id is always
// supplied. One statement: update the scoped row, reconcile its tag and collection links to
// the new set, and return the ItemSavedDetails shape. No matching row → zero-row update →
// ErrNoRows, mapped to 404 by the handler.
//
// Reconciliation runs in one snapshot, so it cannot delete-then-reinsert the same link (the
// reinsert wouldn't see the delete and would collide with the still-live PK row). Instead it
// computes the final link set once (ins_tags resolves names→ids), deletes only links NOT in
// that set, and inserts the set with ON CONFLICT DO NOTHING — delete and insert touch disjoint
// (A,B) pairs, so a kept tag/collection is left untouched rather than removed and re-added.
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.CollectionIds,
		arg.Owner,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.Url,
		arg.Language,
		arg.ItemTypeID,
		arg.ID,
		arg.TagIds,
		arg.TagNames,
	)
	var i UpdateItemRow
	err := row.Scan(
		&i.Description,
		&i.UpdatedAt,
		&i.Url,
		&i.IsFavorite,
		&i.IsPinned,
		&i.Tags,
		&i.Collections,
	)
	return i, err
}
