// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: me.sql

package sqlcdb

import (
	"context"
)

const countFavoriteCollectionsByUser = `-- name: CountFavoriteCollectionsByUser :one
SELECT COUNT(*)::bigint FROM collections WHERE "userId" = $1 AND "isFavorite" = true
`

// Dashboard stat: the user's favorited collection count.
func (q *Queries) CountFavoriteCollectionsByUser(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoriteCollectionsByUser, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFavoriteItemsByUser = `-- name: CountFavoriteItemsByUser :one
SELECT COUNT(*)::bigint FROM items WHERE "userId" = $1 AND "isFavorite" = true
`

// Dashboard stat: the user's favorited item count.
func (q *Queries) CountFavoriteItemsByUser(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoriteItemsByUser, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

// DELETE /me. Every inbound FK to users is ON DELETE CASCADE (accounts, sessions, items,
// item_types, collections, ai_parse_jobs, …), so a single scoped delete removes the whole
// account graph — no child deletes needed.
func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEditorPreferences = `-- name: GetEditorPreferences :one

SELECT "editorPreferences" FROM users WHERE id = $1
`

// Queries for the `me` domain: the authenticated user's own preferences, profile,
// account deletion, and dashboard stats. Every query is scoped by the session userId
// (IDOR-safe) — the id/owner argument is always the caller's own identity, resolved from
// the session, never from user input.
// GET /me/preferences source blob. The raw JSONB is normalized (defaults + clamp) in the
// handler; a NULL column yields a nil slice, which normalizes to the defaults.
func (q *Queries) GetEditorPreferences(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEditorPreferences, id)
	var editorPreferences []byte
	err := row.Scan(&editorPreferences)
	return editorPreferences, err
}

const getItemTypeCountsByUser = `-- name: GetItemTypeCountsByUser :many
SELECT it.name AS name, COUNT(i.id)::bigint AS count
FROM item_types it
LEFT JOIN items i ON i."itemTypeId" = it.id AND i."userId" = $1
WHERE it."isSystem" = true AND it."userId" IS NULL
GROUP BY it.id, it.name
ORDER BY
    CASE it.name
        WHEN 'snippet' THEN 1
        WHEN 'prompt'  THEN 2
        WHEN 'command' THEN 3
        WHEN 'note'    THEN 4
        WHEN 'file'    THEN 5
        WHEN 'image'   THEN 6
        WHEN 'link'    THEN 7
        ELSE 8
    END
`

type GetItemTypeCountsByUserRow struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

// Dashboard per-type distribution: every system item type with the user's item count for it
// (0 when none), ordered by SYSTEM_TYPE_ORDER (mirrors src/lib/utils/constants.ts) so the
// result is stable and matches the legacy getItemTypeDistribution ordering.
func (q *Queries) GetItemTypeCountsByUser(ctx context.Context, owner string) ([]GetItemTypeCountsByUserRow, error) {
	rows, err := q.db.Query(ctx, getItemTypeCountsByUser, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemTypeCountsByUserRow
	for rows.Next() {
		var i GetItemTypeCountsByUserRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEditorPreferences = `-- name: UpdateEditorPreferences :execrows
UPDATE users
SET "editorPreferences" = $1, "updatedAt" = now()
WHERE id = $2
`

type UpdateEditorPreferencesParams struct {
	EditorPreferences []byte `json:"editor_preferences"`
	ID                string `json:"id"`
}

// PATCH /me/preferences write-back. The handler merges the partial patch onto the current
// normalized prefs and re-normalizes before writing, so the stored blob is always valid.
func (q *Queries) UpdateEditorPreferences(ctx context.Context, arg UpdateEditorPreferencesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEditorPreferences, arg.EditorPreferences, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET name = $1, "updatedAt" = now()
WHERE id = $2
RETURNING name, image
`

type UpdateUserNameParams struct {
	Name *string `json:"name"`
	ID   string  `json:"id"`
}

type UpdateUserNameRow struct {
	Name  *string `json:"name"`
	Image *string `json:"image"`
}

// PATCH /me/profile. Sets the display name (NULL clears it). Scoped to the session user;
// returns the updated name + image for the response.
func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (UpdateUserNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.Name, arg.ID)
	var i UpdateUserNameRow
	err := row.Scan(&i.Name, &i.Image)
	return i, err
}
