// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type ContentType string

const (
	ContentTypeTEXT ContentType = "TEXT"
	ContentTypeFILE ContentType = "FILE"
	ContentTypeURL  ContentType = "URL"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType `json:"ContentType"`
	Valid       bool        `json:"valid"` // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type StripeWebhookEventStatus string

const (
	StripeWebhookEventStatusProcessing StripeWebhookEventStatus = "processing"
	StripeWebhookEventStatusProcessed  StripeWebhookEventStatus = "processed"
)

func (e *StripeWebhookEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StripeWebhookEventStatus(s)
	case string:
		*e = StripeWebhookEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StripeWebhookEventStatus: %T", src)
	}
	return nil
}

type NullStripeWebhookEventStatus struct {
	StripeWebhookEventStatus StripeWebhookEventStatus `json:"StripeWebhookEventStatus"`
	Valid                    bool                     `json:"valid"` // Valid is true if StripeWebhookEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStripeWebhookEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StripeWebhookEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StripeWebhookEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStripeWebhookEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StripeWebhookEventStatus), nil
}

type SubscriptionInterval string

const (
	SubscriptionIntervalMonth SubscriptionInterval = "month"
	SubscriptionIntervalYear  SubscriptionInterval = "year"
)

func (e *SubscriptionInterval) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionInterval(s)
	case string:
		*e = SubscriptionInterval(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionInterval: %T", src)
	}
	return nil
}

type NullSubscriptionInterval struct {
	SubscriptionInterval SubscriptionInterval `json:"SubscriptionInterval"`
	Valid                bool                 `json:"valid"` // Valid is true if SubscriptionInterval is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionInterval) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionInterval, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionInterval.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionInterval) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionInterval), nil
}

type Account struct {
	ID                string  `json:"id"`
	UserId            string  `json:"userId"`
	Type              string  `json:"type"`
	Provider          string  `json:"provider"`
	ProviderAccountId string  `json:"providerAccountId"`
	RefreshToken      *string `json:"refresh_token"`
	AccessToken       *string `json:"access_token"`
	ExpiresAt         *int32  `json:"expires_at"`
	TokenType         *string `json:"token_type"`
	Scope             *string `json:"scope"`
	IDToken           *string `json:"id_token"`
	SessionState      *string `json:"session_state"`
	Email             *string `json:"email"`
}

type AiParseJob struct {
	ID               string    `json:"id"`
	Status           string    `json:"status"`
	Progress         int32     `json:"progress"`
	SourceText       string    `json:"sourceText"`
	Error            *string   `json:"error"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
	UserId           string    `json:"userId"`
	OpenaiResponseId *string   `json:"openaiResponseId"`
	StreamCursor     *int32    `json:"streamCursor"`
	CollectionIds    []string  `json:"collectionIds"`
	CollectionName   *string   `json:"collectionName"`
	SourceItemId     *string   `json:"sourceItemId"`
	SourceName       *string   `json:"sourceName"`
	Truncated        bool      `json:"truncated"`
	CommittedCount   int32     `json:"committedCount"`
	CommittedByType  []byte    `json:"committedByType"`
}

type AiParseJobItem struct {
	ID           string    `json:"id"`
	Order        int32     `json:"order"`
	ItemTypeName string    `json:"itemTypeName"`
	Title        string    `json:"title"`
	Content      *string   `json:"content"`
	Url          *string   `json:"url"`
	Language     *string   `json:"language"`
	Description  *string   `json:"description"`
	Tags         []string  `json:"tags"`
	CreatedAt    time.Time `json:"createdAt"`
	JobId        string    `json:"jobId"`
	UserId       string    `json:"userId"`
	Trashed      bool      `json:"trashed"`
}

type Collection struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Description   *string   `json:"description"`
	IsFavorite    bool      `json:"isFavorite"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	UserId        string    `json:"userId"`
	DefaultTypeId *string   `json:"defaultTypeId"`
}

type Item struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	ContentType ContentType `json:"contentType"`
	Content     *string     `json:"content"`
	FileUrl     *string     `json:"fileUrl"`
	FileName    *string     `json:"fileName"`
	FileSize    *int32      `json:"fileSize"`
	Url         *string     `json:"url"`
	Description *string     `json:"description"`
	IsFavorite  bool        `json:"isFavorite"`
	IsPinned    bool        `json:"isPinned"`
	Language    *string     `json:"language"`
	CreatedAt   time.Time   `json:"createdAt"`
	UpdatedAt   time.Time   `json:"updatedAt"`
	UserId      string      `json:"userId"`
	ItemTypeId  string      `json:"itemTypeId"`
	ImageHeight *int32      `json:"imageHeight"`
	ImageWidth  *int32      `json:"imageWidth"`
}

type ItemCollection struct {
	ItemId       string    `json:"itemId"`
	CollectionId string    `json:"collectionId"`
	AddedAt      time.Time `json:"addedAt"`
}

type ItemTag struct {
	A string `json:"A"`
	B string `json:"B"`
}

type ItemType struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Icon     string  `json:"icon"`
	Color    string  `json:"color"`
	IsSystem bool    `json:"isSystem"`
	UserId   *string `json:"userId"`
}

type Session struct {
	ID           string    `json:"id"`
	SessionToken string    `json:"sessionToken"`
	UserId       string    `json:"userId"`
	Expires      time.Time `json:"expires"`
}

type StripeWebhookEvent struct {
	ID          string                   `json:"id"`
	EventType   string                   `json:"eventType"`
	Status      StripeWebhookEventStatus `json:"status"`
	CreatedAt   time.Time                `json:"createdAt"`
	ProcessedAt *time.Time               `json:"processedAt"`
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID                         string                `json:"id"`
	Email                      string                `json:"email"`
	EmailVerified              *time.Time            `json:"emailVerified"`
	Name                       *string               `json:"name"`
	Image                      *string               `json:"image"`
	Password                   *string               `json:"password"`
	IsPro                      bool                  `json:"isPro"`
	StripeCustomerId           *string               `json:"stripeCustomerId"`
	StripeSubscriptionId       *string               `json:"stripeSubscriptionId"`
	CreatedAt                  time.Time             `json:"createdAt"`
	UpdatedAt                  time.Time             `json:"updatedAt"`
	EditorPreferences          []byte                `json:"editorPreferences"`
	StripeSubscriptionStart    *time.Time            `json:"stripeSubscriptionStart"`
	StripeCurrentPeriodEnd     *time.Time            `json:"stripeCurrentPeriodEnd"`
	ProExpiredAt               *time.Time            `json:"proExpiredAt"`
	StripeCancelAtPeriodEnd    bool                  `json:"stripeCancelAtPeriodEnd"`
	StripeSubscriptionInterval *SubscriptionInterval `json:"stripeSubscriptionInterval"`
	StripeLastSyncAt           *time.Time            `json:"stripeLastSyncAt"`
	StripeSubscriptionStatus   *string               `json:"stripeSubscriptionStatus"`
	CredentialEmail            *string               `json:"credentialEmail"`
	CredentialEmailVerified    *time.Time            `json:"credentialEmailVerified"`
}

type VerificationToken struct {
	Identifier string    `json:"identifier"`
	Token      string    `json:"token"`
	Expires    time.Time `json:"expires"`
}
