// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlcdb

import (
	"context"
	"time"
)

const searchCollections = `-- name: SearchCollections :many
SELECT
    c.id,
    c.name,
    c.description,
    c."isFavorite",
    (SELECT COUNT(*)::int FROM item_collections ic WHERE ic."collectionId" = c.id) AS "itemCount"
FROM collections c
WHERE c."userId" = $1
    AND (
        c.name ILIKE $2
        OR c.description ILIKE $2
    )
ORDER BY c."updatedAt" DESC
LIMIT 10
`

type SearchCollectionsParams struct {
	Owner   string `json:"owner"`
	Pattern string `json:"pattern"`
}

type SearchCollectionsRow struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsFavorite  bool    `json:"isFavorite"`
	ItemCount   int32   `json:"itemCount"`
}

// Collection hits: name/description ILIKE, capped at 10, updatedAt desc. Returns the
// SidebarCollection shape (no type chips, no dates); dominantColor is always null in search
// (parity with mapSidebarCollection's default).
func (q *Queries) SearchCollections(ctx context.Context, arg SearchCollectionsParams) ([]SearchCollectionsRow, error) {
	rows, err := q.db.Query(ctx, searchCollections, arg.Owner, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCollectionsRow
	for rows.Next() {
		var i SearchCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsFavorite,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItems = `-- name: SearchItems :many

SELECT
    i.id,
    i.title,
    i."createdAt",
    i.url,
    i."fileName",
    i."fileSize",
    i."isFavorite",
    i."isPinned",
    it.name AS "itemTypeName",
    COALESCE(LEFT(i.description, 150), '')::text AS "descriptionPreview",
    COALESCE(LEFT(i.content, 150), '')::text AS "contentPreview",
    COALESCE(array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL), '{}'::text[])::text[] AS tags
FROM items i
JOIN item_types it ON it.id = i."itemTypeId"
LEFT JOIN "_ItemTags" itag ON itag."A" = i.id
LEFT JOIN tags t ON t.id = itag."B"
WHERE i."userId" = $1
    AND (
        i.title ILIKE $2
        OR i.description ILIKE $2
        OR i.content ILIKE $2
        OR EXISTS (
            SELECT 1 FROM "_ItemTags" it2
            JOIN tags tg ON tg.id = it2."B"
            WHERE it2."A" = i.id AND tg.name ILIKE $2
        )
    )
GROUP BY i.id, it.name
ORDER BY i."updatedAt" DESC
LIMIT 20
`

type SearchItemsParams struct {
	Owner   string `json:"owner"`
	Pattern string `json:"pattern"`
}

type SearchItemsRow struct {
	ID                 string    `json:"id"`
	Title              string    `json:"title"`
	CreatedAt          time.Time `json:"createdAt"`
	Url                *string   `json:"url"`
	FileName           *string   `json:"fileName"`
	FileSize           *int32    `json:"fileSize"`
	IsFavorite         bool      `json:"isFavorite"`
	IsPinned           bool      `json:"isPinned"`
	ItemTypeName       string    `json:"itemTypeName"`
	DescriptionPreview string    `json:"descriptionPreview"`
	ContentPreview     string    `json:"contentPreview"`
	Tags               []string  `json:"tags"`
}

// Search domain queries (Phase 2). Uncached global search, scoped by session userId.
// Fuzzy substring match via ILIKE against the pg_trgm GIN-indexed columns (parity with the
// Next app's `contains`/`insensitive` mode — NOT a tsvector rewrite). The query term is
// wrapped as '%' || $query || '%' by the caller-supplied pattern arg.
// Item hits: title/description/content/tag-name ILIKE, capped at 20, updatedAt desc.
// Returns the same LightItem projection as the item list (so a search hit opens a fully
// hydrated drawer).
func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]SearchItemsRow, error) {
	rows, err := q.db.Query(ctx, searchItems, arg.Owner, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchItemsRow
	for rows.Next() {
		var i SearchItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.Url,
			&i.FileName,
			&i.FileSize,
			&i.IsFavorite,
			&i.IsPinned,
			&i.ItemTypeName,
			&i.DescriptionPreview,
			&i.ContentPreview,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
